-- ════════════════════════════════════════════════════════════════
-- SIGFAR Hub — Catálogo APIs — DDL + Seed 32 APIs
-- Ejecutar: docker exec -i sigfar-hub-db psql -U sigfar -d sigfar < db/init/04_apis.sql
-- ════════════════════════════════════════════════════════════════

CREATE TABLE hgu_hub_apis (
    id                      SERIAL PRIMARY KEY,
    nombre                  VARCHAR(100) NOT NULL,
    descripcion             TEXT,
    url_base                VARCHAR(500),
    url_docs                VARCHAR(500),
    url_test                VARCHAR(500),
    auth_type               VARCHAR(50) CHECK (auth_type IN ('NONE','API_KEY','BEARER','OAUTH')),
    env_var_key             VARCHAR(100),
    limite_gratis           VARCHAR(200),
    bloque                  VARCHAR(50) NOT NULL
                            CHECK (bloque IN ('IA_GENERATIVA','MEDICAMENTOS','EVIDENCIA',
                                              'CODIFICACION','SEGURIDAD','CALCULADORAS','HOSPITAL')),
    categoria_radar         VARCHAR(50),
    estado                  VARCHAR(20) DEFAULT 'PENDIENTE'
                            CHECK (estado IN ('CONECTADA','EN_APEX','PENDIENTE','FUTURO')),
    donde_integrada         VARCHAR(200),
    modulo_uso              VARCHAR(200),
    caso_uso                TEXT,
    propuesta_ia            TEXT,
    prioridad               VARCHAR(5) CHECK (prioridad IN ('P1','P2','P3')),
    tiempo_estimado         VARCHAR(50),
    ultimo_test             TIMESTAMP,
    ultimo_test_ok          BOOLEAN,
    ultimo_test_latencia_ms INTEGER,
    favorito                BOOLEAN DEFAULT FALSE,
    nota_usuario            TEXT
);

CREATE INDEX idx_hub_apis_bloque ON hgu_hub_apis(bloque);
CREATE INDEX idx_hub_apis_estado ON hgu_hub_apis(estado);
CREATE INDEX idx_hub_apis_prioridad ON hgu_hub_apis(prioridad);

-- ════════════════════════════════════════════════════════════════
-- Seed: 32 APIs del roadmap SIGFAR Hub
-- ════════════════════════════════════════════════════════════════

INSERT INTO hgu_hub_apis (nombre, descripcion, url_base, url_docs, url_test, auth_type, env_var_key, limite_gratis, bloque, estado, donde_integrada, modulo_uso, caso_uso, prioridad, tiempo_estimado) VALUES

-- ═══ BLOQUE: IA_GENERATIVA (6) ═══
('Groq Cloud',
 'API de inferencia ultra-rápida. Modelos Llama 3.3 70B, Mixtral. Latencia < 200ms.',
 'https://api.groq.com/openai/v1',
 'https://console.groq.com/docs/quickstart',
 'https://api.groq.com/openai/v1/models',
 'BEARER', 'OPENAI_API_KEY',
 '14.400 req/día, 30 req/min en 70B',
 'IA_GENERATIVA', 'CONECTADA', 'SIGFAR Hub',
 'POF, EM/PRM, Sigfarita, Radar IA',
 'Generación de planes farmacoterapéuticos, detección de errores de medicación, chat IA Sigfarita para Dirección del Servicio, clasificación de artículos en Radar IA',
 'P1', 'Conectada'),

('Google Gemini',
 'API multimodal de Google. Gemini 2.0 Flash gratis. Visión, texto, código.',
 'https://generativelanguage.googleapis.com/v1beta',
 'https://ai.google.dev/docs',
 'https://generativelanguage.googleapis.com/v1beta/models?key=test',
 'API_KEY', 'GEMINI_API_KEY',
 '1.500 req/día gratis, 15 req/min',
 'IA_GENERATIVA', 'PENDIENTE', NULL,
 'Segundo modelo para consenso multi-IA, análisis de imágenes de preparaciones',
 'Comparar diagnósticos farmacoterapéuticos entre Llama y Gemini. Visión artificial para verificación de preparaciones en cabina',
 'P1', '30 min'),

('Mistral AI',
 'Modelo europeo RGPD compliant. Mistral Large, Codestral.',
 'https://api.mistral.ai/v1',
 'https://docs.mistral.ai',
 'https://api.mistral.ai/v1/models',
 'BEARER', 'MISTRAL_API_KEY',
 'Tier gratuito básico disponible',
 'IA_GENERATIVA', 'PENDIENTE', NULL,
 'Tercer modelo para consenso, cumplimiento RGPD europeo',
 'Modelo alternativo para validación farmacoterapéutica con garantías de privacidad europeas',
 'P3', '30 min'),

('HuggingFace Inference',
 'Acceso a modelos especializados: Meditron, BioGPT, PubMedBERT.',
 'https://api-inference.huggingface.co/models',
 'https://huggingface.co/docs/api-inference',
 'https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct',
 'BEARER', 'HF_API_KEY',
 'Limitado gratis, modelos pequeños sin cola',
 'IA_GENERATIVA', 'PENDIENTE', NULL,
 'Modelos biomédicos especializados: Meditron-70B, BioGPT, PubMedBERT',
 'Usar Meditron para validación especializada de antibióticos. PubMedBERT para clasificación de artículos del Radar IA',
 'P3', '1-2h'),

('LM Studio Local',
 'Servidor de inferencia local. Modelos Qwen, Llama, Meditron sin internet.',
 'http://localhost:1234/v1',
 'https://lmstudio.ai/docs',
 'http://localhost:1234/v1/models',
 'NONE', NULL,
 'Sin límite, hardware local',
 'IA_GENERATIVA', 'PENDIENTE', NULL,
 'Inferencia sin internet para datos sensibles, Qwen 2.5 72B en local',
 'Ejecutar validaciones farmacoterapéuticas con datos de pacientes sin salir de la red del hospital. Ideal para cumplimiento RGPD estricto',
 'P2', '1-2h'),

('Cerebro IA Substrate AI',
 'Modelo dedicado 70-120B dentro de la red del hospital. Proyecto conjunto con Substrate AI.',
 'https://servidor-hospital/v1',
 'https://substrate.ai',
 NULL,
 'BEARER', 'SUBSTRATE_API_KEY',
 'Sin límite, infraestructura local',
 'IA_GENERATIVA', 'FUTURO', NULL,
 'Modelo dedicado para el CHGUV, entrenado con datos propios',
 'Desplegar modelo fine-tuneado con guías del CHGUV para validación farmacoterapéutica con conocimiento institucional',
 'P3', 'Proyecto largo'),

-- ═══ BLOQUE: MEDICAMENTOS (7) ═══
('CIMA/AEMPS',
 'Centro de Información de Medicamentos de la AEMPS. Fichas técnicas, prospectos, alertas de todos los medicamentos autorizados en España.',
 'https://cima.aemps.es/cima/rest',
 'https://cima.aemps.es/cima/resources/docs/CIMA_REST_API.pdf',
 'https://cima-proxy.ximomachi.workers.dev/cima/rest/medicamento?cn=694546',
 'NONE', NULL,
 'Sin límite via proxy Cloudflare Workers',
 'MEDICAMENTOS', 'EN_APEX', 'APEX Plataforma SIGFAR — HGU_PKG_CIMA v3.0',
 'P15 chat CIMA, validación farmacoterapéutica',
 'Consulta de fichas técnicas durante la validación de prescripciones. Verificación de indicaciones, contraindicaciones, dosis máximas, interacciones',
 'P1', 'Conectada'),

('OpenFDA',
 'API de la FDA: eventos adversos FAERS, recalls, etiquetado de medicamentos.',
 'https://api.fda.gov',
 'https://open.fda.gov/apis/',
 'https://api.fda.gov/drug/event.json?limit=1',
 'NONE', 'OPENFDA_API_KEY',
 'Sin key: 240 req/min. Con key: 120.000 req/día',
 'MEDICAMENTOS', 'PENDIENTE', NULL,
 'Farmacovigilancia, detección de señales de seguridad',
 'Cruzar medicamentos del paciente con eventos adversos FAERS para alertas proactivas de seguridad en la validación',
 'P1', '30 min'),

('DrugBank Open',
 'Base de datos farmacológica: interacciones, targets, farmacocinética.',
 'https://go.drugbank.com/releases/latest',
 'https://dev.drugbank.com/guides/api',
 NULL,
 'NONE', NULL,
 'Datos abiertos descargables gratuitamente',
 'MEDICAMENTOS', 'PENDIENTE', NULL,
 'Interacciones farmacológicas, datos PK',
 'Enriquecer la detección de interacciones en P15 con datos de mecanismo y severidad de DrugBank',
 'P2', '1-2h'),

('RxNorm/NLM',
 'Nomenclatura normalizada de medicamentos. Mapeo entre códigos nacionales.',
 'https://rxnav.nlm.nih.gov/REST',
 'https://lhncbc.nlm.nih.gov/RxNav/APIs/',
 'https://rxnav.nlm.nih.gov/REST/rxcui.json?name=aspirin',
 'NONE', NULL,
 'Sin límite',
 'MEDICAMENTOS', 'PENDIENTE', NULL,
 'Normalización nomenclatura, mapeo internacional',
 'Mapear medicamentos españoles a terminología internacional para comparaciones y búsquedas cross-border',
 'P3', '1-2h'),

('ChEMBL',
 'Base de datos de bioactividad molecular del EBI. Datos farmacológicos abiertos.',
 'https://www.ebi.ac.uk/chembl/api/data',
 'https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services',
 'https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL25.json',
 'NONE', NULL,
 'Sin límite',
 'MEDICAMENTOS', 'PENDIENTE', NULL,
 'Datos farmacológicos para investigación',
 'Consultar datos de bioactividad para informes de farmacocinética clínica y selección de antimicrobianos',
 'P3', '1-2h'),

('DailyMed/NLM',
 'Prospectos y fichas técnicas de medicamentos de la NLM (USA).',
 'https://dailymed.nlm.nih.gov/dailymed/services/v2',
 'https://dailymed.nlm.nih.gov/dailymed/app-support-web-services.cfm',
 'https://dailymed.nlm.nih.gov/dailymed/services/v2/drugnames.json?drug_name=aspirin&pagesize=1',
 'NONE', NULL,
 'Sin límite',
 'MEDICAMENTOS', 'PENDIENTE', NULL,
 'Fichas técnicas USA complementarias a CIMA',
 'Complementar CIMA con información de prospectos USA para medicamentos extranjeros o de uso compasivo',
 'P3', '30 min'),

('SNS Nomenclátor',
 'Catálogo nacional de medicamentos del SNS con precios. CSV mensual de datos.gob.es.',
 'https://datos.gob.es/es/catalogo/e00142801-nomenclator-de-producto-farmaceutico',
 'https://www.sanidad.gob.es/profesionales/nomenclator.do',
 NULL,
 'NONE', NULL,
 'Sin límite, descarga CSV mensual',
 'MEDICAMENTOS', 'EN_APEX', 'APEX GestionAX',
 'Catálogo medicamentos, precios, GFT',
 'Mantener actualizado el catálogo del hospital con precios oficiales del SNS para análisis de farmacoeconomía',
 'P1', 'Conectada'),

-- ═══ BLOQUE: EVIDENCIA (6) ═══
('PubMed/NCBI',
 'Base de datos con 35M+ artículos biomédicos. eUtils API para búsqueda y recuperación.',
 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils',
 'https://www.ncbi.nlm.nih.gov/books/NBK25501/',
 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&retmode=json&retmax=1&term=pharmacy',
 'API_KEY', 'NCBI_API_KEY',
 '10 req/s con API key, 3 req/s sin key',
 'EVIDENCIA', 'EN_APEX', 'APEX Plataforma SIGFAR + Hub Radar IA',
 'P15 chat bibliografía, Radar IA escaneo',
 'Búsqueda de evidencia durante la validación farmacoterapéutica. Escaneo automático de novedades en Radar IA',
 'P1', 'Conectada'),

('ClinicalTrials.gov',
 'Registro de ensayos clínicos del NIH. API v2 con búsqueda avanzada.',
 'https://clinicaltrials.gov/api/v2',
 'https://clinicaltrials.gov/data-api/about-api',
 'https://clinicaltrials.gov/api/v2/studies?query.term=pharmacy&pageSize=1',
 'NONE', NULL,
 'Sin límite',
 'EVIDENCIA', 'EN_APEX', 'APEX Plataforma SIGFAR P15 chat + Hub Radar IA',
 'P15 ensayos clínicos, Radar IA',
 'Buscar ensayos clínicos relevantes para pacientes con opciones terapéuticas limitadas. Monitorizar nuevos ensayos en Radar IA',
 'P1', 'Conectada'),

('Europe PMC',
 'Artículos europeos open access. Incluye preprints y tesis.',
 'https://www.ebi.ac.uk/europepmc/webservices/rest',
 'https://europepmc.org/RestfulWebService',
 'https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=pharmacy&format=json&pageSize=1',
 'NONE', NULL,
 'Sin límite',
 'EVIDENCIA', 'PENDIENTE', NULL,
 'Búsqueda de evidencia europea, artículos open access',
 'Complementar PubMed con artículos europeos open access para el Radar IA y consultas bibliográficas',
 'P3', '30 min'),

('Semantic Scholar',
 'Búsqueda semántica de papers con IA. Graph API con embeddings.',
 'https://api.semanticscholar.org/graph/v1',
 'https://api.semanticscholar.org/',
 'https://api.semanticscholar.org/graph/v1/paper/search?query=pharmacy&limit=1&fields=title',
 'NONE', NULL,
 '100 req/5 min sin key',
 'EVIDENCIA', 'PENDIENTE', NULL,
 'Radar IA escaneo, búsqueda semántica de evidencia',
 'Búsqueda semántica avanzada de artículos para el Radar IA. Encontrar papers similares por embeddings',
 'P2', '15 min'),

('Unpaywall',
 'Localiza versiones open access de artículos de pago.',
 'https://api.unpaywall.org/v2',
 'https://unpaywall.org/products/api',
 NULL,
 'API_KEY', NULL,
 '100.000 req/día con email como key',
 'EVIDENCIA', 'PENDIENTE', NULL,
 'Acceso a artículos completos para validación',
 'Encontrar versiones gratuitas de artículos citados en validaciones farmacoterapéuticas',
 'P3', '15 min'),

('CrossRef',
 'Metadatos de publicaciones científicas. Resolución de DOIs.',
 'https://api.crossref.org',
 'https://api.crossref.org/swagger-ui/index.html',
 'https://api.crossref.org/works?query=pharmacy&rows=1',
 'NONE', NULL,
 'Sin límite con email en User-Agent',
 'EVIDENCIA', 'PENDIENTE', NULL,
 'Metadatos bibliográficos, resolución DOIs',
 'Enriquecer referencias bibliográficas con metadatos completos (autores, journal, impact factor)',
 'P3', '15 min'),

-- ═══ BLOQUE: CODIFICACION (4) ═══
('SNOMED CT',
 'Terminología clínica internacional estandarizada. Browser API.',
 'https://browser.ihtsdotools.org/snowstorm/snomed-ct',
 'https://confluence.ihtsdotools.org/display/DOCSNOWSTORM',
 'https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN/concepts?term=aspirin&limit=1',
 'NONE', NULL,
 'Gratis con licencia de uso (España tiene licencia nacional)',
 'CODIFICACION', 'PENDIENTE', NULL,
 'Codificación diagnósticos y procedimientos',
 'Mapear diagnósticos de texto libre a códigos SNOMED para análisis automatizado y búsquedas estandarizadas',
 'P3', '1-2h'),

('ICD-11 OMS',
 'Clasificación Internacional de Enfermedades v11. API REST oficial de la OMS.',
 'https://id.who.int/icd',
 'https://icd.who.int/icdapi',
 'https://id.who.int/icd/release/11/2024-01/mms/search?q=diabetes&flatMode=true',
 'BEARER', 'ICD_API_TOKEN',
 'Sin límite con registro gratuito',
 'CODIFICACION', 'PENDIENTE', NULL,
 'Códigos diagnósticos internacionales',
 'Clasificar automáticamente diagnósticos de pacientes para análisis poblacional y farmacovigilancia',
 'P3', '1-2h'),

('ATC/WHO',
 'Sistema de Clasificación Anatómica Terapéutica Química. DDD (Dosis Diaria Definida).',
 'https://www.whocc.no/atc_ddd_index',
 'https://www.whocc.no/atc_ddd_methodology/',
 NULL,
 'NONE', NULL,
 'Sin límite, datos descargables',
 'CODIFICACION', 'PENDIENTE', NULL,
 'Clasificación ATC, cálculo DDD para indicadores PROA',
 'Calcular DDD/1000 estancias para indicadores PROA y benchmarking de consumo antibiótico',
 'P3', '1-2h'),

('LOINC',
 'Códigos estandarizados para analíticas de laboratorio.',
 'https://loinc.org/api',
 'https://loinc.org/kb/users-guide/',
 NULL,
 'API_KEY', 'LOINC_API_KEY',
 'Gratis con registro',
 'CODIFICACION', 'PENDIENTE', NULL,
 'Estandarización resultados de laboratorio',
 'Mapear parámetros analíticos del hospital a códigos LOINC para interoperabilidad y alertas automatizadas',
 'P3', '1-2h'),

-- ═══ BLOQUE: SEGURIDAD (3) ═══
('WHO VigiAccess',
 'Portal de farmacovigilancia mundial de la OMS. Reportes de reacciones adversas.',
 'https://vigiaccess.org',
 'https://www.who-umc.org/vigibase/vigiaccess/',
 NULL,
 'NONE', NULL,
 'Gratis, acceso web',
 'SEGURIDAD', 'PENDIENTE', NULL,
 'Farmacovigilancia mundial, señales de seguridad',
 'Consultar perfil de seguridad mundial de medicamentos durante la validación. Complementar datos FAERS de OpenFDA',
 'P2', '1-2h'),

('EMA Open Data',
 'Datos abiertos de la Agencia Europea del Medicamento. Medicamentos autorizados, informes de seguridad.',
 'https://open.ema.europa.eu/api',
 'https://open.ema.europa.eu/',
 'https://open.ema.europa.eu/api/v1/medicines?page=1&page_size=1',
 'NONE', NULL,
 'Sin límite',
 'SEGURIDAD', 'PENDIENTE', NULL,
 'Medicamentos europeos, informes seguridad PRAC',
 'Consultar estado de autorización y alertas de seguridad de medicamentos en Europa',
 'P3', '30 min'),

('ISMP Medication Safety',
 'Institute for Safe Medication Practices. Alertas de seguridad y medicamentos de alto riesgo.',
 'https://www.ismp.org',
 'https://www.ismp.org/resources',
 NULL,
 'NONE', NULL,
 'Gratis parcial, alertas públicas',
 'SEGURIDAD', 'PENDIENTE', NULL,
 'Alertas seguridad, lista medicamentos alto riesgo',
 'Mantener actualizada la lista de medicamentos de alto riesgo y alertas de seguridad para la validación',
 'P3', '1-2h'),

-- ═══ BLOQUE: CALCULADORAS (2) ═══
('MDCalc',
 'Calculadoras médicas: Cockcroft-Gault, Child-Pugh, SOFA, APACHE, CHA2DS2-VASc.',
 'https://www.mdcalc.com',
 'https://www.mdcalc.com/api',
 NULL,
 'NONE', NULL,
 'Gratis limitado, API parcial',
 'CALCULADORAS', 'PENDIENTE', NULL,
 'Scores clínicos para ajuste de dosis',
 'Calcular automáticamente Cockcroft-Gault, Child-Pugh y otros scores para ajuste de dosis en P42 farmacocinética',
 'P3', '1-2h'),

('eGFR Calculator NKF',
 'Calculadora de filtrado glomerular estimado de la National Kidney Foundation.',
 'https://www.kidney.org/professionals/kdoqi/gfr_calculator',
 'https://www.kidney.org',
 NULL,
 'NONE', NULL,
 'Gratis',
 'CALCULADORAS', 'PENDIENTE', NULL,
 'Función renal para ajuste de dosis',
 'Calcular eGFR CKD-EPI 2021 automáticamente para ajuste de dosis en insuficiencia renal',
 'P3', '30 min'),

-- ═══ BLOQUE: HOSPITAL (5) ═══
('FHIR R4 HL7',
 'Estándar de interoperabilidad sanitaria. Conectar con Hosix, ICCA, Florence.',
 'https://hl7.org/fhir/R4',
 'https://hl7.org/fhir/R4/http.html',
 NULL,
 'BEARER', NULL,
 'Estándar abierto, implementación local',
 'HOSPITAL', 'FUTURO', NULL,
 'Interoperabilidad con HCE Hosix, ICCA, Florence',
 'Conectar SIGFAR Hub con la historia clínica electrónica del CHGUV via FHIR para lectura automática de diagnósticos, analíticas y prescripciones',
 'P3', 'Proyecto largo'),

('ICCA UCI',
 'Sistema de información de UCI. Datos de pacientes críticos en tiempo real.',
 'red hospital',
 NULL,
 NULL,
 'NONE', NULL,
 'Interno, red hospital',
 'HOSPITAL', 'FUTURO', NULL,
 'Datos UCI: constantes, ventilación, sedación, balance hídrico',
 'Leer datos en tiempo real de pacientes UCI para alertas farmacoterapéuticas proactivas (TDM, interacciones con sedación)',
 'P3', 'Proyecto largo'),

('OMA Prescripción',
 'Sistema de prescripción electrónica del hospital.',
 'red hospital',
 NULL,
 NULL,
 'NONE', NULL,
 'Interno, red hospital',
 'HOSPITAL', 'FUTURO', NULL,
 'Prescripciones electrónicas de planta',
 'Integrar prescripciones en tiempo real para validación automática 24/7 con IA',
 'P3', 'Proyecto largo'),

('Versia NP',
 'Software de prescripción de nutrición parenteral.',
 'red hospital',
 NULL,
 NULL,
 'NONE', NULL,
 'Interno, red hospital',
 'HOSPITAL', 'FUTURO', NULL,
 'Prescripción NP, integración con P36 nutrición',
 'Leer prescripciones de NP de Versia para alimentar automáticamente el módulo P36 de nutrición artificial',
 'P3', 'Proyecto largo'),

('ExactaMix / ChemoMaker',
 'Robots de elaboración de nutrición parenteral y quimioterapia.',
 'red hospital',
 NULL,
 NULL,
 'NONE', NULL,
 'Interno, red hospital',
 'HOSPITAL', 'FUTURO', NULL,
 'Elaboración robotizada NP y quimio',
 'Enviar órdenes de elaboración a robots ExactaMix (NP) y ChemoMaker (quimio) desde SIGFAR con verificación IA',
 'P3', 'Proyecto largo');
