-- ════════════════════════════════════════════════════════════════
-- SIGFAR Hub — Algoritmos ML — DDL + Seed 25 algoritmos
-- Ejecutar: docker exec -i sigfar-hub-db psql -U sigfar -d sigfar < db/init/05_ml_algoritmos.sql
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS hgu_ml_algoritmos (
    id                      SERIAL PRIMARY KEY,
    nombre                  VARCHAR(200) NOT NULL,
    nombre_tecnico          VARCHAR(100),
    descripcion             TEXT,
    tipo_ml                 VARCHAR(50) NOT NULL
                            CHECK (tipo_ml IN ('SUPERVISADO','NO_SUPERVISADO','REFUERZO','DEEP_LEARNING','NLP','SERIES_TEMPORALES','BAYESIANO')),
    subtipo                 VARCHAR(100),
    categoria_farmacia      VARCHAR(50) NOT NULL
                            CHECK (categoria_farmacia IN ('VALIDACION','FARMACOCINETICA','NUTRICION','PROA',
                                                          'ELABORACION','STOCK_LOGISTICA','ROBOTICA',
                                                          'FARMACOECONOMIA','CUADRO_MANDOS','REGULACION')),
    caso_uso                TEXT,
    ejemplo_sigfar          TEXT,
    librerias_python        VARCHAR(500),
    complejidad             VARCHAR(20) CHECK (complejidad IN ('BAJA','MEDIA','ALTA','MUY_ALTA')),
    datos_necesarios        TEXT,
    dataset_ejemplo         VARCHAR(500),
    paper_referencia        VARCHAR(500),
    paper_extra_1           VARCHAR(500),
    paper_extra_2           VARCHAR(500),
    url_documentacion       VARCHAR(500),
    estado_sigfar_hub       VARCHAR(20) DEFAULT 'NO_IMPLEMENTADO'
                            CHECK (estado_sigfar_hub IN ('IMPLEMENTADO','EN_DESARROLLO','PLANIFICADO','NO_IMPLEMENTADO')),
    modulo_sigfar           VARCHAR(100),
    donde_implementar       VARCHAR(200),
    propuesta_ia            TEXT,
    relevancia              INTEGER DEFAULT 50,
    prioridad               VARCHAR(5) CHECK (prioridad IN ('P1','P2','P3')),
    favorito                BOOLEAN DEFAULT FALSE,
    prioridad_usuario       VARCHAR(10) CHECK (prioridad_usuario IN ('ALTA','MEDIA','BAJA')),
    nota_usuario            TEXT,
    tags                    VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_ml_categoria ON hgu_ml_algoritmos(categoria_farmacia);
CREATE INDEX IF NOT EXISTS idx_ml_tipo ON hgu_ml_algoritmos(tipo_ml);
CREATE INDEX IF NOT EXISTS idx_ml_estado ON hgu_ml_algoritmos(estado_sigfar_hub);
CREATE INDEX IF NOT EXISTS idx_ml_favorito ON hgu_ml_algoritmos(favorito);

-- ════════════════════════════════════════════════════════════════
-- Seed: 25 algoritmos ML para farmacia hospitalaria
-- ════════════════════════════════════════════════════════════════

INSERT INTO hgu_ml_algoritmos (nombre, nombre_tecnico, descripcion, tipo_ml, subtipo, categoria_farmacia, caso_uso, ejemplo_sigfar, librerias_python, complejidad, datos_necesarios, dataset_ejemplo, paper_referencia, url_documentacion, estado_sigfar_hub, modulo_sigfar, donde_implementar, relevancia, prioridad, tags) VALUES

-- ═══ VALIDACION (7) ═══
('Random Forest para detección de EM/PRM',
 'RandomForestClassifier',
 'Clasificador ensemble que combina múltiples árboles de decisión para detectar errores de medicación y problemas relacionados con medicamentos a partir de variables del paciente, tratamiento y analíticas.',
 'SUPERVISADO', 'Clasificación', 'VALIDACION',
 'Detectar automáticamente PRM tipo 3 (RAM potencial) y PRM tipo 1 (medicamento innecesario) analizando combinaciones fármaco-diagnóstico-analítica.',
 'Integrar en P15 Dashboard paciente: al cargar un paciente, el modelo analiza sus tratamientos activos y genera alertas priorizadas de EM/PRM con probabilidad.',
 'scikit-learn, pandas, numpy, imbalanced-learn',
 'MEDIA', 'hgu_tratamientos + hgu_analiticas + hgu_emprm_lineas (histórico etiquetado)',
 'https://physionet.org/content/mimiciii/', 'https://doi.org/10.1016/j.ijmedinf.2023.105032',
 'https://scikit-learn.org/stable/modules/ensemble.html#random-forests',
 'NO_IMPLEMENTADO', 'P15, HUB', 'SIGFAR Hub', 90, 'P1',
 'random-forest,clasificacion,emprm,deteccion-errores'),

('XGBoost para predicción de interacciones medicamentosas',
 'XGBClassifier',
 'Gradient boosting extremo para predecir la probabilidad y severidad de interacciones medicamentosas (DDI) en politerapia, usando features moleculares y clínicas.',
 'SUPERVISADO', 'Clasificación', 'VALIDACION',
 'Predecir DDI severas en pacientes polimedicados al añadir un nuevo fármaco, alertando antes de la validación farmacéutica.',
 'En el módulo de validación P15: al prescribir un nuevo medicamento, XGBoost evalúa riesgo de DDI contra todos los activos del paciente.',
 'xgboost, scikit-learn, pandas, rdkit',
 'ALTA', 'Pares de fármacos con DDI conocidas (DrugBank/OpenFDA) + datos locales de prescripción',
 'https://www.drugbank.com/releases/latest',
 'https://doi.org/10.1093/bioinformatics/btaa501',
 'https://xgboost.readthedocs.io/',
 'NO_IMPLEMENTADO', 'P15', 'SIGFAR Hub', 85, 'P1',
 'xgboost,ddi,interacciones,prediccion'),

('NLP extracción de entidades clínicas',
 'BioBERT / spaCy',
 'Modelos de procesamiento de lenguaje natural para extraer entidades clínicas (medicamentos, dosis, frecuencias, diagnósticos) de texto libre en evoluciones clínicas.',
 'NLP', 'NER', 'VALIDACION',
 'Extraer automáticamente medicamentos y dosis de las notas clínicas de evolución para cruzar con la prescripción electrónica.',
 'Procesar hgu_evolucion.texto para extraer entidades y compararlas con hgu_tratamientos, detectando discrepancias prescripción-administración.',
 'spacy, transformers, biobert, scispacy',
 'ALTA', 'hgu_evolucion (texto libre de evoluciones clínicas)',
 'https://huggingface.co/dmis-lab/biobert-v1.1',
 'https://doi.org/10.1093/bioinformatics/btz682',
 'https://allenai.github.io/scispacy/',
 'NO_IMPLEMENTADO', 'P15, HUB', 'SIGFAR Hub', 80, 'P2',
 'nlp,ner,biobert,spacy,extraccion-entidades'),

('Isolation Forest para prescripciones atípicas',
 'IsolationForest',
 'Algoritmo de detección de anomalías que identifica prescripciones que se desvían significativamente del patrón habitual (dosis extremas, combinaciones raras).',
 'NO_SUPERVISADO', 'Detección de anomalías', 'VALIDACION',
 'Detectar dosis fuera de rango, frecuencias inusuales o combinaciones de medicamentos no habituales como señal de posible error de prescripción.',
 'Analizar hgu_tratamientos para cada nuevo ingreso: si dosis/frecuencia/vía se desvían >2σ del patrón histórico, alertar al farmacéutico.',
 'scikit-learn, pandas, numpy',
 'BAJA', 'hgu_tratamientos (histórico de prescripciones)',
 NULL,
 'https://doi.org/10.1109/ICDM.2008.17',
 'https://scikit-learn.org/stable/modules/outlier_detection.html',
 'NO_IMPLEMENTADO', 'P15', 'SIGFAR Hub', 75, 'P2',
 'isolation-forest,anomalias,prescripciones-atipicas'),

('LightGBM para scoring de complejidad farmacoterapéutica',
 'LGBMClassifier',
 'Gradient boosting ligero para calcular automáticamente el score de complejidad de un paciente en las 14 dimensiones del modelo SIGFAR P40.',
 'SUPERVISADO', 'Clasificación multiclase', 'VALIDACION',
 'Automatizar el cálculo del score de complejidad (actualmente manual en P40) usando datos de tratamientos, analíticas y diagnósticos.',
 'Entrenar con las puntuaciones históricas de P40 (14 dimensiones) para predecir automáticamente el nivel de complejidad al ingreso.',
 'lightgbm, scikit-learn, pandas',
 'MEDIA', 'hgu_score_seguimiento + hgu_tratamientos + hgu_analiticas',
 NULL,
 'https://doi.org/10.1016/j.ejphar.2021.174276',
 'https://lightgbm.readthedocs.io/',
 'NO_IMPLEMENTADO', 'P40, HUB', 'SIGFAR Hub + APEX', 85, 'P1',
 'lightgbm,complejidad,scoring,p40'),

('Autoencoders para detección de anomalías en analíticas',
 'Autoencoder (Keras)',
 'Red neuronal autoencoder que aprende el patrón normal de analíticas de un paciente y detecta desviaciones significativas que podrían indicar RAM o deterioro clínico.',
 'DEEP_LEARNING', 'Detección de anomalías', 'VALIDACION',
 'Monitorizar analíticas seriadas (función renal, hepática, hemograma) para detectar cambios bruscos correlacionados con medicamentos nefrotóxicos o hepatotóxicos.',
 'Pipeline que procesa hgu_analiticas diariamente: si reconstrucción del autoencoder supera umbral, generar alerta de "analítica anómala + fármaco sospechoso".',
 'tensorflow, keras, scikit-learn, pandas',
 'ALTA', 'hgu_analiticas (series temporales de valores analíticos por paciente)',
 'https://physionet.org/content/mimiciii/',
 'https://doi.org/10.1038/s41598-021-87762-0',
 'https://keras.io/examples/generative/vae/',
 'NO_IMPLEMENTADO', 'P15, HUB', 'SIGFAR Hub', 70, 'P2',
 'autoencoder,deep-learning,analiticas,ram'),

('Med2Vec embeddings de medicamentos',
 'Med2Vec',
 'Embeddings vectoriales de medicamentos basados en patrones de co-prescripción. Permite encontrar similitudes farmacológicas no evidentes y sugerir alternativas terapéuticas.',
 'DEEP_LEARNING', 'Embeddings', 'VALIDACION',
 'Sugerir alternativas terapéuticas cuando un medicamento no está disponible (desabastecimiento) basándose en similitud de patrones de uso.',
 'Entrenar con hgu_tratamientos: los vectores de medicamentos permiten buscar "fármaco similar" cuando hay rotura de stock o alergias.',
 'gensim, pytorch, numpy',
 'ALTA', 'hgu_tratamientos + hgu_catalogo_hospital (patrones de co-prescripción)',
 NULL,
 'https://doi.org/10.1145/2939672.2939823',
 NULL,
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub', 65, 'P3',
 'med2vec,embeddings,alternativas,similitud'),

-- ═══ FARMACOCINETICA (3) ═══
('MAP Bayesiano para individualización posológica',
 'MAP Estimation',
 'Estimación Maximum A Posteriori para ajuste de dosis individualizado combinando modelos PK poblacionales con datos del paciente (concentraciones plasmáticas, covariables).',
 'BAYESIANO', 'Estimación', 'FARMACOCINETICA',
 'Ajuste de dosis de vancomicina, aminoglucósidos, antiepilépticos y otros fármacos con estrecho margen terapéutico usando datos del paciente.',
 'YA IMPLEMENTADO en P42: el farmacéutico introduce concentraciones y el sistema calcula dosis óptima y predicción de niveles.',
 'scipy, numpy, pandas',
 'ALTA', 'Concentraciones plasmáticas + covariables del paciente (peso, creatinina, edad)',
 NULL,
 'https://doi.org/10.1007/s40262-019-00769-1',
 'https://docs.scipy.org/doc/scipy/reference/optimize.html',
 'IMPLEMENTADO', 'P42', 'APEX Plataforma SIGFAR', 95, 'P1',
 'map-bayesiano,farmacocinetica,vancomicina,tdm,implementado'),

('Red Neuronal para predicción de AUC de vancomicina',
 'MLPRegressor / LSTM',
 'Red neuronal que predice el AUC0-24 de vancomicina a partir de datos demográficos, renales y de dosificación, evitando la necesidad de múltiples muestras sanguíneas.',
 'DEEP_LEARNING', 'Regresión', 'FARMACOCINETICA',
 'Predecir AUC con una sola muestra de nivel valle, reduciendo extracciones sanguíneas en pacientes con infecciones graves por SARM.',
 'Complementar P42: tras primera dosis, con un solo nivel, predecir AUC y recomendar ajuste sin esperar a estado estacionario.',
 'tensorflow, keras, scikit-learn, pandas',
 'MUY_ALTA', 'Datos PK de vancomicina (concentraciones, dosis, intervalos, función renal)',
 NULL,
 'https://doi.org/10.1128/aac.01005-21',
 'https://keras.io/',
 'NO_IMPLEMENTADO', 'P42', 'APEX Plataforma SIGFAR', 80, 'P2',
 'rna,auc,vancomicina,prediccion,deep-learning'),

('PopPK con NLME modelos poblacionales locales',
 'Pmetrics / NLME',
 'Modelado farmacocinético poblacional con ecuaciones no lineales de efectos mixtos para generar modelos PK propios del hospital con datos de pacientes locales.',
 'BAYESIANO', 'Modelado poblacional', 'FARMACOCINETICA',
 'Crear modelos PK adaptados a la población del CHGUV (diferente a poblaciones publicadas) para mejorar predicción de niveles.',
 'Exportar datos de P42 + analíticas para generar modelos PopPK propios que mejoren los genéricos publicados.',
 'Pmetrics (R), nlmixr2 (R), scipy, pymc',
 'MUY_ALTA', 'Datos PK completos de múltiples pacientes (concentraciones, dosis, covariables)',
 NULL,
 'https://doi.org/10.1002/psp4.12404',
 'https://lapkb.github.io/Pmetrics/',
 'NO_IMPLEMENTADO', 'P42', 'Substrate AI + APEX', 75, 'P3',
 'poppk,nlme,modelos-poblacionales,r'),

-- ═══ NUTRICION (2) ═══
('Regresión múltiple para predicción de gasto energético',
 'LinearRegression / ElasticNet',
 'Modelo de regresión para predecir el gasto energético total (GET) del paciente a partir de variables antropométricas, bioquímicas y clínicas.',
 'SUPERVISADO', 'Regresión', 'NUTRICION',
 'Calcular automáticamente las necesidades calóricas del paciente para ajustar la nutrición parenteral/enteral, sustituyendo calorimetría indirecta.',
 'En P36 Nutrición: al ingresar datos del paciente, el modelo predice GET y sugiere composición de NP adaptada.',
 'scikit-learn, pandas, numpy',
 'BAJA', 'Datos antropométricos + bioquímica + calorimetrías indirectas (gold standard)',
 NULL,
 'https://doi.org/10.1016/j.clnu.2019.12.004',
 'https://scikit-learn.org/stable/modules/linear_model.html',
 'NO_IMPLEMENTADO', 'P36', 'APEX Plataforma SIGFAR', 70, 'P2',
 'regresion,get,nutricion,calorias'),

('KMeans clustering de perfiles nutricionales',
 'KMeans',
 'Agrupación no supervisada de pacientes según perfil nutricional (albúmina, prealbúmina, PCR, IMC, score NRS-2002) para protocolizar intervenciones.',
 'NO_SUPERVISADO', 'Clustering', 'NUTRICION',
 'Identificar fenotipos de desnutrición (sarcopénica, inflamatoria, mixta) para aplicar protocolos diferenciados de soporte nutricional.',
 'Agrupar pacientes de hgu_analiticas + hgu_pacientes por perfil nutricional y visualizar clusters en Dashboard P15.',
 'scikit-learn, pandas, matplotlib',
 'BAJA', 'hgu_analiticas (albúmina, prealbúmina, PCR) + hgu_pacientes (IMC, edad)',
 NULL,
 'https://doi.org/10.1016/j.clnu.2020.03.012',
 'https://scikit-learn.org/stable/modules/clustering.html#k-means',
 'NO_IMPLEMENTADO', 'P36, HUB', 'SIGFAR Hub', 60, 'P3',
 'kmeans,clustering,nutricion,fenotipos'),

-- ═══ PROA (2) ═══
('Gradient Boosting para predicción de resistencias antimicrobianas',
 'GradientBoostingClassifier',
 'Predice la probabilidad de resistencia de un microorganismo a antibióticos específicos basándose en antibiogramas previos del hospital y perfil del paciente.',
 'SUPERVISADO', 'Clasificación', 'PROA',
 'Al prescribir un antibiótico empírico, el modelo indica probabilidad de resistencia para cada opción, guiando la elección inicial.',
 'En P43 PROA: al detectar prescripción empírica, mostrar probabilidades de resistencia basadas en microbiología local + perfil paciente.',
 'scikit-learn, xgboost, pandas',
 'ALTA', 'Antibiogramas del hospital + perfil paciente (unidad, comorbilidades, ATB previos)',
 NULL,
 'https://doi.org/10.1093/cid/ciac764',
 'https://scikit-learn.org/stable/modules/ensemble.html#gradient-boosting',
 'NO_IMPLEMENTADO', 'P43', 'APEX Plataforma SIGFAR', 88, 'P1',
 'gradient-boosting,resistencias,proa,antibioticos'),

('Survival Analysis para duración óptima de antibioterapia',
 'CoxPH / KaplanMeier',
 'Análisis de supervivencia para determinar la duración óptima de tratamiento antibiótico, identificando el punto de equilibrio beneficio/riesgo.',
 'SUPERVISADO', 'Análisis de supervivencia', 'PROA',
 'Alertar cuando un paciente excede la duración óptima de ATB según su perfil, apoyando la intervención del farmacéutico PROA para desescalada.',
 'En P43: mostrar curva de supervivencia y probabilidad de curación vs duración, alertando al farmacéutico cuando se supera el punto óptimo.',
 'lifelines, scikit-survival, pandas',
 'MEDIA', 'Tratamientos ATB con fecha inicio/fin + desenlace clínico (curación/recaída)',
 NULL,
 'https://doi.org/10.1093/jac/dkab049',
 'https://lifelines.readthedocs.io/',
 'NO_IMPLEMENTADO', 'P43', 'APEX Plataforma SIGFAR', 78, 'P2',
 'survival-analysis,cox,proa,duracion-atb'),

-- ═══ STOCK_LOGISTICA (3) ═══
('SARIMA para predicción de consumo de medicamentos',
 'SARIMAX',
 'Modelo de series temporales estacional para predecir el consumo futuro de medicamentos considerando estacionalidad (gripe, alergias) y tendencias.',
 'SERIES_TEMPORALES', 'Predicción', 'STOCK_LOGISTICA',
 'Predecir consumo semanal/mensual de cada fármaco para optimizar pedidos a almacén y evitar roturas de stock.',
 'Conectar con GestionAX (2M consumos): entrenar SARIMA por fármaco y generar predicciones para las próximas 4-8 semanas.',
 'statsmodels, pandas, numpy',
 'MEDIA', 'GestionAX consumos históricos (2M registros, 3 años)',
 NULL,
 'https://doi.org/10.1016/j.ijpe.2020.107956',
 'https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub + GestionAX', 82, 'P1',
 'sarima,series-temporales,consumo,stock'),

('Prophet para estacionalidad de consumo farmacéutico',
 'Prophet',
 'Modelo de Facebook/Meta para forecasting con estacionalidad múltiple (semanal, mensual, anual) y detección automática de cambios de tendencia.',
 'SERIES_TEMPORALES', 'Forecasting', 'STOCK_LOGISTICA',
 'Forecasting de consumo con detección automática de festivos, vacaciones, picos estacionales (gripe, alergia) y cambios de protocolo.',
 'Dashboard en Hub que muestra predicción a 8 semanas para los 50 fármacos de mayor consumo/coste con intervalos de confianza.',
 'prophet, pandas',
 'BAJA', 'GestionAX consumos diarios por fármaco',
 NULL,
 'https://doi.org/10.7717/peerj-cs.1052',
 'https://facebook.github.io/prophet/',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub + GestionAX', 80, 'P1',
 'prophet,forecasting,estacionalidad,consumo'),

('Logistic Regression para riesgo de caducidad',
 'LogisticRegression',
 'Modelo simple para predecir la probabilidad de que un lote de medicamento caduque antes de ser consumido, basándose en rotación histórica.',
 'SUPERVISADO', 'Clasificación binaria', 'STOCK_LOGISTICA',
 'Identificar lotes con alta probabilidad de caducidad para priorizar su dispensación (FEFO) o redistribución entre servicios.',
 'Integrar en gestión de stock: alertar sobre lotes con >70% probabilidad de caducar en los próximos 60 días.',
 'scikit-learn, pandas',
 'BAJA', 'Stock actual + historial de consumo por lote + caducidades reales',
 NULL, NULL,
 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub + GestionAX', 68, 'P2',
 'logistic-regression,caducidad,stock,fefo'),

-- ═══ FARMACOECONOMIA (2) ═══
('ElasticNet para predicción de gasto farmacéutico',
 'ElasticNet',
 'Regresión regularizada que predice el gasto farmacéutico por servicio/paciente combinando penalización L1 y L2 para seleccionar variables relevantes.',
 'SUPERVISADO', 'Regresión', 'FARMACOECONOMIA',
 'Predecir el gasto mensual por servicio clínico para detectar desviaciones y apoyar la negociación presupuestaria.',
 'Dashboard Jefatura: predicción de gasto a 3 meses por servicio con desglose por grupo terapéutico, comparando con presupuesto asignado.',
 'scikit-learn, pandas, numpy',
 'MEDIA', 'GestionAX consumos valorados + datos actividad por servicio',
 NULL,
 'https://doi.org/10.1016/j.healthpol.2020.05.004',
 'https://scikit-learn.org/stable/modules/linear_model.html#elastic-net',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub + GestionAX', 72, 'P2',
 'elasticnet,gasto,prediccion,farmacoeconomia'),

('Apriori/FPGrowth para patrones de co-prescripción',
 'FPGrowth',
 'Algoritmo de reglas de asociación que descubre patrones frecuentes de co-prescripción para identificar sinergias terapéuticas o combinaciones de riesgo.',
 'NO_SUPERVISADO', 'Reglas de asociación', 'FARMACOECONOMIA',
 'Descubrir qué medicamentos se prescriben juntos frecuentemente para: 1) detectar combinaciones de riesgo, 2) negociar precios por volumen.',
 'Analizar hgu_tratamientos: generar reglas tipo "si paracetamol+tramadol → 80% también metamizol" para protocolización.',
 'mlxtend, pandas',
 'BAJA', 'hgu_tratamientos (combinaciones de fármacos por episodio)',
 NULL,
 'https://doi.org/10.1145/170036.170072',
 'https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/fpgrowth/',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub', 58, 'P3',
 'fpgrowth,apriori,co-prescripcion,asociacion'),

-- ═══ CUADRO_MANDOS (2) ═══
('Prophet para forecasting de indicadores SEFH',
 'Prophet',
 'Forecasting de KPIs farmacéuticos SEFH (intervenciones, validaciones, NP preparadas, consultas) con estacionalidad y tendencia.',
 'SERIES_TEMPORALES', 'Forecasting', 'CUADRO_MANDOS',
 'Predecir los indicadores SEFH a cierre de mes/trimestre para anticipar desviaciones y justificar recursos.',
 'En Jefatura/Sigfarita: "¿cuántas validaciones cerraremos este mes?" → Prophet predice con intervalo de confianza.',
 'prophet, pandas, plotly',
 'BAJA', 'Indicadores mensuales SEFH (histórico 3+ años)',
 NULL, NULL,
 'https://facebook.github.io/prophet/',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub', 65, 'P2',
 'prophet,kpi,sefh,forecasting,indicadores'),

('KMeans clustering de actividad farmacéutica',
 'KMeans',
 'Agrupación de farmacéuticos por perfil de actividad (validaciones, intervenciones, consultorías, NP) para equilibrar cargas de trabajo.',
 'NO_SUPERVISADO', 'Clustering', 'CUADRO_MANDOS',
 'Identificar desequilibrios en la distribución de carga de trabajo entre farmacéuticos y optimizar asignación de tareas.',
 'Dashboard Jefatura: visualizar clusters de actividad y detectar farmacéuticos sobrecargados o infrautilizados.',
 'scikit-learn, pandas, matplotlib',
 'BAJA', 'Registro de actividad por farmacéutico (validaciones, intervenciones, etc.)',
 NULL, NULL,
 'https://scikit-learn.org/stable/modules/clustering.html',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub', 55, 'P3',
 'kmeans,clustering,actividad,farmaceuticos'),

-- ═══ REGULACION (1) ═══
('DistilBERT para clasificación de alertas AEMPS',
 'DistilBERT',
 'Modelo NLP basado en transformers para clasificar automáticamente alertas y notas informativas de la AEMPS por relevancia para el hospital.',
 'NLP', 'Clasificación de texto', 'REGULACION',
 'Clasificar automáticamente las alertas AEMPS diarias por relevancia para el hospital (afecta a GFT, requiere acción inmediata, informativa).',
 'Feed de alertas AEMPS → DistilBERT clasifica → las de alta relevancia aparecen automáticamente en Radar IA y Dashboard Jefatura.',
 'transformers, torch, scikit-learn',
 'ALTA', 'Alertas AEMPS históricas clasificadas manualmente (training set)',
 NULL,
 'https://doi.org/10.48550/arXiv.1910.01108',
 'https://huggingface.co/distilbert-base-multilingual-cased',
 'NO_IMPLEMENTADO', 'HUB', 'SIGFAR Hub', 62, 'P3',
 'distilbert,nlp,aemps,alertas,clasificacion'),

-- ═══ ELABORACION (1) ═══
('CNN/ResNet para verificación visual de preparaciones',
 'ResNet50',
 'Red neuronal convolucional para verificación visual de preparaciones estériles (NP, quimioterapia) comparando imagen de la preparación con la prescripción.',
 'DEEP_LEARNING', 'Clasificación de imagen', 'ELABORACION',
 'Fotografiar cada preparación de NP/QT y verificar automáticamente color, volumen, turbidez y presencia de partículas antes de dispensar.',
 'Cámara en cabina de flujo laminar → imagen → ResNet clasifica como OK/NOK → alerta si discrepancia con prescripción.',
 'tensorflow, keras, opencv, torchvision',
 'MUY_ALTA', 'Imágenes etiquetadas de preparaciones (OK/NOK) — requiere captura en cabina',
 NULL,
 'https://doi.org/10.1016/j.ejpb.2021.11.002',
 'https://pytorch.org/vision/stable/models/resnet.html',
 'NO_IMPLEMENTADO', 'P36, P37', 'Substrate AI', 60, 'P3',
 'cnn,resnet,vision,elaboracion,verificacion'),

-- ═══ ROBOTICA (1) ═══
('Reinforcement Learning para optimización de rutas de dispensación',
 'DQN / PPO',
 'Aprendizaje por refuerzo para optimizar las rutas de los robots AGV de dispensación en el hospital, minimizando tiempo y maximizando entregas.',
 'REFUERZO', 'Optimización', 'ROBOTICA',
 'Optimizar las rutas de dispensación de carros de medicación por planta, minimizando tiempo de entrega y maximizando eficiencia de batería.',
 'Simular entorno hospitalario con plantas/servicios → entrenar agente RL → integrar con sistema de dispensación robotizada.',
 'stable-baselines3, gymnasium, pytorch',
 'MUY_ALTA', 'Layout del hospital + datos de entregas + tiempos de desplazamiento',
 NULL,
 'https://doi.org/10.1016/j.artmed.2021.102073',
 'https://stable-baselines3.readthedocs.io/',
 'NO_IMPLEMENTADO', NULL, 'Substrate AI', 45, 'P3',
 'rl,reinforcement-learning,rutas,dispensacion,agv');
