-- ═══════════════════════════════════════════════════════════════
-- SIGFAR Hub — Módulo H: Herramientas IA
-- Catálogo interactivo de herramientas IA para farmacéuticos
-- 8 categorías × ~55 herramientas con fichas completas
-- Ejecutar: docker exec -i sigfar-hub-db psql -U sigfar -d sigfar < db/init/10_herramientas_ia.sql
-- ═══════════════════════════════════════════════════════════════

DROP TABLE IF EXISTS hgu_herramientas_ia CASCADE;

CREATE TABLE hgu_herramientas_ia (
    id                  SERIAL PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    url                 VARCHAR(500) NOT NULL,
    logo_emoji          VARCHAR(10),
    descripcion_corta   VARCHAR(200) NOT NULL,
    descripcion_larga   TEXT,
    categoria           VARCHAR(30) NOT NULL CHECK (categoria IN (
                            'LLM_GENERALISTA','BUSQUEDA_CIENTIFICA','GESTION_DOCUMENTAL',
                            'PRESENTACIONES','ESCRITURA','DESARROLLO','IMAGEN_MULTIMEDIA','SALUD_FARMA'
                        )),
    empresa             VARCHAR(100),
    plan_gratuito       TEXT,
    plan_pago           TEXT,
    ventajas            JSONB,
    inconvenientes      JSONB,
    casos_uso_fh        JSONB,
    nivel_dificultad    VARCHAR(10) DEFAULT 'FACIL' CHECK (nivel_dificultad IN ('FACIL','MEDIO','AVANZADO')),
    privacidad          VARCHAR(20) CHECK (privacidad IN ('CLOUD_ANONIMIZAR','CLOUD_CON_DPA','LOCAL','MIXTO')),
    requiere_cuenta     BOOLEAN DEFAULT TRUE,
    tags                JSONB,
    orden               INTEGER DEFAULT 0,
    favorito            BOOLEAN DEFAULT FALSE,
    nota_usuario        TEXT,
    valoracion          INTEGER CHECK (valoracion BETWEEN 1 AND 5),
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_herramientas_categoria ON hgu_herramientas_ia(categoria);
CREATE INDEX idx_herramientas_nivel ON hgu_herramientas_ia(nivel_dificultad);
CREATE INDEX idx_herramientas_favorito ON hgu_herramientas_ia(favorito);
CREATE INDEX idx_herramientas_tags ON hgu_herramientas_ia USING GIN(tags);

-- ═══════════════════════════════════════════════════════════════
-- SEED: ~55 herramientas en 8 categorías
-- ═══════════════════════════════════════════════════════════════

INSERT INTO hgu_herramientas_ia
    (nombre, url, logo_emoji, descripcion_corta, descripcion_larga, categoria, empresa,
     plan_gratuito, plan_pago, ventajas, inconvenientes, casos_uso_fh,
     nivel_dificultad, privacidad, requiere_cuenta, tags, orden)
VALUES

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 1: LLM_GENERALISTA (6 herramientas)
-- ═══════════════════════════════════════════════════════════════

('ChatGPT', 'https://chat.openai.com', '🧠',
 'LLM generalista con GPTs personalizables, Canvas para edición y DALL-E integrado',
 'ChatGPT de OpenAI es el LLM más utilizado del mundo. Permite conversaciones en lenguaje natural, creación de GPTs personalizados, edición colaborativa con Canvas, generación de imágenes con DALL-E, análisis de documentos y código. Ideal como primer contacto con IA generativa.',
 'LLM_GENERALISTA', 'OpenAI',
 'GPT-4o mini gratis, GPTs limitados, Canvas, DALL-E 2/día',
 'Plus 20$/mes: GPT-4o ilimitado, DALL-E ilimitado, voz avanzada. Team 25$/mes.',
 '["Modelo más popular y versátil","GPTs personalizables para tareas repetitivas","Canvas: edición colaborativa de textos","DALL-E integrado para imágenes","Plugins y conexión a internet","Buena comprensión de contexto clínico"]',
 '["Datos van a servidores OpenAI (USA)","Puede alucinar con datos clínicos específicos","Plan gratuito limitado en modelo","No siempre cita fuentes verificables"]',
 '[{"titulo":"Consulta clínica compleja","descripcion":"Paciente con insuficiencia renal + hepática: ¿ajuste de dosis de meropenem? ChatGPT razona sobre PK, genera recomendación con dosis y monitorización.","dominio":"VALIDACION"},
   {"titulo":"Redacción de informes PITM","descripcion":"Pega los datos del fármaco y pide: genera informe para Comisión FyT con estructura GENESIS. Revisa y adapta el borrador.","dominio":"GESTION"},
   {"titulo":"Generación de protocolos","descripcion":"Describe el protocolo que necesitas y ChatGPT genera borrador completo con indicaciones, contraindicaciones, dosis, monitorización y bibliografía.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["validación","TDM","PROA","nutrición","investigación","formación","redacción"]', 1),

('Claude', 'https://claude.ai', '🟣',
 'Razonamiento profundo, contexto 200K tokens, Artifacts y Projects para documentos',
 'Claude de Anthropic destaca por su razonamiento profundo y contexto de 200.000 tokens (equivalente a ~500 páginas). Projects permite subir documentos y trabajar sobre ellos. Artifacts genera código, documentos y visualizaciones en panel lateral. Claude Code permite programar desde terminal hablando en español.',
 'LLM_GENERALISTA', 'Anthropic',
 'Claude 3.5 Sonnet gratis (limitado), Projects, Artifacts',
 'Pro 20$/mes: Claude Opus, uso ilimitado, prioridad. Team 30$/mes.',
 '["200K tokens de contexto (puede leer un libro entero)","Razonamiento más profundo que GPT-4 en tareas complejas","Projects: sube documentos y trabaja sobre ellos","Artifacts: genera código y documentos editables","Claude Code: programación agéntica desde terminal","Excelente en español"]',
 '["Datos en servidores Anthropic (USA)","Plan gratuito bastante limitado en uso","Sin generación de imágenes nativa","Menos plugins que ChatGPT"]',
 '[{"titulo":"Análisis de guías clínicas extensas","descripcion":"Sube la guía ESPEN 2023 completa (80 págs) a un Project y pregunta: ¿cuándo iniciar NP en paciente crítico con fallo intestinal? Claude responde citando párrafos exactos.","dominio":"NUTRICION"},
   {"titulo":"Revisión farmacoterapéutica compleja","descripcion":"Pega el tratamiento completo de un paciente polimedicado (15+ fármacos). Claude analiza interacciones, ajustes renales, duplicidades y genera POF estructurado.","dominio":"VALIDACION"},
   {"titulo":"Programar calculadoras clínicas","descripcion":"Con Claude Code: crea una calculadora de Cockcroft-Gault + ajuste de vancomicina en React, hablando en español. Genera código funcional directamente.","dominio":"DESARROLLO"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["validación","nutrición","investigación","programación","documentos"]', 2),

('Gemini', 'https://gemini.google.com', '💎',
 'Multimodal (texto+imagen+vídeo), Deep Research, integración Google Workspace',
 'Gemini de Google es un modelo multimodal que procesa texto, imágenes y vídeo. Deep Research realiza investigaciones exhaustivas con múltiples búsquedas. Integrado en Google Workspace (Docs, Sheets, Gmail). NotebookLM es un producto separado pero complementario.',
 'LLM_GENERALISTA', 'Google',
 'Gemini 2.0 Flash gratis, Deep Research limitado, integración Google',
 'Advanced 22€/mes: Gemini Ultra, 1M tokens, Deep Research ilimitado, 2TB Google One.',
 '["Multimodal: analiza imágenes y vídeos","Deep Research: investigación exhaustiva automatizada","Integrado en Google Docs, Sheets, Gmail","1M tokens de contexto en versión avanzada","Grounding con búsqueda Google en tiempo real","Bueno en razonamiento científico"]',
 '["Datos en servidores Google","A veces menos preciso que Claude en razonamiento","Deep Research puede tardar varios minutos","Interfaz menos pulida que ChatGPT"]',
 '[{"titulo":"Análisis de imagen clínica","descripcion":"Sube foto de un preparado magistral y pregunta si el aspecto es correcto: color, homogeneidad, partículas. Gemini analiza la imagen y compara con lo esperado.","dominio":"ELABORACION"},
   {"titulo":"Deep Research sobre biosimilares","descripcion":"Pide: investiga toda la evidencia disponible sobre switch de adalimumab original a biosimilar. Gemini ejecuta múltiples búsquedas y genera informe completo con citas.","dominio":"INVESTIGACION"},
   {"titulo":"Automatizar hojas de cálculo","descripcion":"En Google Sheets con tus datos de consumos: pide a Gemini que genere fórmulas para calcular DDD, coste/DDD, variación interanual y gráficos automáticos.","dominio":"GESTION"}]',
 'FACIL', 'CLOUD_CON_DPA', TRUE,
 '["multimodal","investigación","Google Workspace","Deep Research"]', 3),

('Copilot', 'https://copilot.microsoft.com', '🔵',
 'Integrado en Office 365/Teams, acceso GPT-4, ideal entorno hospitalario Microsoft',
 'Microsoft Copilot integra GPT-4 en todo el ecosistema Microsoft: Word, Excel, PowerPoint, Teams, Outlook. Ideal para hospitales que ya usan Microsoft 365. Puede analizar datos en Excel, redactar en Word, resumir reuniones en Teams.',
 'LLM_GENERALISTA', 'Microsoft',
 'Copilot básico gratis con GPT-4, búsqueda web Bing',
 'Copilot Pro 22€/mes: integración Office 365. Copilot for Microsoft 365: 30€/usuario/mes.',
 '["Integrado en Word, Excel, PowerPoint, Teams, Outlook","GPT-4 gratis en versión básica","Ideal si el hospital ya usa Microsoft 365","Puede analizar Excel con lenguaje natural","Resume reuniones de Teams automáticamente"]',
 '["Integración Office requiere licencia cara","Menos flexible que ChatGPT/Claude standalone","Limitado en contexto vs Claude","Dependencia ecosistema Microsoft"]',
 '[{"titulo":"Resumir sesiones clínicas en Teams","descripcion":"Tras una sesión de servicio en Teams, Copilot genera resumen automático: temas tratados, decisiones, tareas pendientes, y lo envía por email a los asistentes.","dominio":"GESTION"},
   {"titulo":"Análisis de consumos en Excel","descripcion":"Abre el Excel de consumos de GestionAX y pregunta en lenguaje natural: ¿cuáles son los 10 fármacos con mayor incremento de gasto vs año anterior? Copilot genera tabla y gráfico.","dominio":"GESTION"},
   {"titulo":"Preparar presentación de comisión","descripcion":"En PowerPoint: genera presentación para Comisión FyT con los datos que le proporcionas. Diseño profesional automático.","dominio":"COMUNICACION"}]',
 'FACIL', 'CLOUD_CON_DPA', TRUE,
 '["Office 365","Teams","Excel","presentaciones","hospital"]', 4),

('Groq', 'https://groq.com', '⚡',
 'Inferencia ultrarrápida gratuita (Llama 3.3 70B), API gratis, ideal para prototipar',
 'Groq ofrece inferencia de LLMs open-source a velocidad récord gracias a sus chips LPU. Llama 3.3 70B gratis con 14.400 peticiones/día. Es el motor de IA de SIGFAR Hub: genera POF, detecta EM/PRM, alimenta Sigfarita, Radar IA, y todos los módulos con IA.',
 'LLM_GENERALISTA', 'Groq Inc.',
 'Gratis: Llama 3.3 70B, 14.400 req/día, 30 req/min, API REST',
 'Pay-as-you-go: $0.59/M tokens input, $0.79/M tokens output (Llama 70B).',
 '["Gratis con límites generosos (14.400 req/día)","Velocidad récord: ~800 tokens/segundo","API compatible con OpenAI SDK","Modelos open-source (Llama, Mixtral)","Ideal para prototipar sin coste","Motor de SIGFAR Hub"]',
 '["Sin interfaz chat propia (solo API/playground)","Modelos open-source pueden ser menos precisos que GPT-4","Rate limits en plan gratuito","Sin multimodalidad todavía"]',
 '[{"titulo":"Motor de SIGFAR Hub","descripcion":"Groq es el cerebro de SIGFAR: genera POF con pipeline multiagente, detecta EM/PRM, alimenta Sigfarita, enriquece Radar IA, genera propuestas estratégicas. 0€/mes.","dominio":"VALIDACION"},
   {"titulo":"Prototipar nuevas funcionalidades","descripcion":"Antes de implementar: prueba prompts en el playground de Groq para validar que el modelo genera las respuestas esperadas. Ajusta temperature y max_tokens.","dominio":"DESARROLLO"},
   {"titulo":"Batch analysis nocturno","descripcion":"Con 14.400 req/día, puedes analizar 422 pacientes cada noche automáticamente. Coste: 0€. Vigilancia proactiva 24/7.","dominio":"VALIDACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["API","gratuito","Llama","prototipar","SIGFAR"]', 5),

('LM Studio', 'https://lmstudio.ai', '💻',
 'LLMs locales en tu portátil sin enviar datos a la nube, 100% privacidad',
 'LM Studio permite ejecutar modelos de IA directamente en tu ordenador, sin conexión a internet. Soporta Llama, Qwen, Mistral, Meditron y otros. Los datos NUNCA salen de tu máquina. Ideal para datos sensibles de pacientes. API compatible con OpenAI en localhost:1234.',
 'LLM_GENERALISTA', 'LM Studio',
 'Gratis: descarga modelos GGUF, interfaz chat, API local, sin límites',
 'Gratis (software open-source). Solo necesitas hardware suficiente (16GB+ RAM).',
 '["100% privacidad: datos nunca salen del ordenador","Sin coste: gratis y sin límites de uso","Sin internet: funciona offline","API compatible OpenAI en localhost:1234","Modelos médicos: Meditron, BioMistral","Ideal para datos sensibles de pacientes"]',
 '["Requiere hardware potente (16GB+ RAM, GPU recomendada)","Modelos locales menos potentes que GPT-4/Claude","Configuración inicial requiere conocimientos técnicos","Velocidad inferior a servicios cloud"]',
 '[{"titulo":"Análisis de datos sensibles","descripcion":"Paciente con VIH + hepatitis C + tratamiento complejo: analiza con Meditron-70B en local. Los datos del paciente NUNCA salen del ordenador del farmacéutico.","dominio":"VALIDACION"},
   {"titulo":"Entorno sin internet","descripcion":"En zonas del hospital sin WiFi o durante caídas de red: LM Studio funciona offline. Puedes consultar interacciones y ajustes de dosis sin conexión.","dominio":"VALIDACION"},
   {"titulo":"Modelo dedicado para SIGFAR","descripcion":"Futuro: entrenar modelo fine-tuned con datos anonimizados de SIGFAR y ejecutarlo en LM Studio. IA personalizada para el servicio.","dominio":"DESARROLLO"}]',
 'AVANZADO', 'LOCAL', FALSE,
 '["local","privacidad","offline","datos sensibles","Meditron"]', 6),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 2: BUSQUEDA_CIENTIFICA (10 herramientas)
-- ═══════════════════════════════════════════════════════════════

('Perplexity AI', 'https://perplexity.ai', '🔍',
 'Buscador IA con citas verificables en tiempo real',
 'Perplexity es un motor de búsqueda potenciado por IA que busca en internet en tiempo real y genera respuestas con citas verificables. A diferencia de ChatGPT, cada afirmación viene con su fuente. Ideal para buscar información actualizada con confianza.',
 'BUSQUEDA_CIENTIFICA', 'Perplexity AI',
 'Gratis: búsquedas ilimitadas, modelo estándar, citas',
 'Pro 20$/mes: GPT-4, Claude, búsquedas Pro ilimitadas, subir archivos.',
 '["Citas verificables en cada respuesta","Busca internet en tiempo real","Mejor que Google para preguntas complejas","Interfaz limpia y directa","Focus modes: Academic, Writing, etc."]',
 '["Plan gratuito usa modelo más básico","No siempre accede a papers de pago","Puede simplificar respuestas complejas","Menos profundo que una revisión sistemática"]',
 '[{"titulo":"Buscar evidencia rápida para planta","descripcion":"Enfermería pregunta: ¿se puede triturar omeprazol MUPS? Perplexity busca ficha técnica + guías y responde con cita en 10 segundos.","dominio":"VALIDACION"},
   {"titulo":"Verificar interacción fármaco-alimento","descripcion":"¿Interacción warfarina con zumo de arándanos? Perplexity busca PubMed + UpToDate y devuelve respuesta con nivel de evidencia.","dominio":"VALIDACION"},
   {"titulo":"Estado del arte de un tema","descripcion":"¿Cuál es la evidencia actual sobre IA en TDM de vancomicina? Perplexity genera resumen con 10+ citas de artículos recientes.","dominio":"INVESTIGACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["búsqueda","evidencia","citas","verificable","rápido"]', 1),

('Consensus', 'https://consensus.app', '📊',
 'Busca millones de papers y muestra grado de acuerdo científico (SÍ/NO/INCIERTO)',
 'Consensus es un buscador académico que no solo encuentra papers, sino que analiza sus conclusiones y muestra si la evidencia científica dice SÍ, NO o es INCIERTA sobre tu pregunta. Basado en Semantic Scholar. Ideal para decisiones basadas en evidencia.',
 'BUSQUEDA_CIENTIFICA', 'Consensus',
 'Gratis: 20 búsquedas/mes, resultados básicos, Consensus Meter',
 'Premium 10$/mes: búsquedas ilimitadas, filtros avanzados, exportar.',
 '["Muestra grado de consenso científico (SÍ/NO/INCIERTO)","Basado en millones de papers reales","Ideal para decisiones basadas en evidencia","Interfaz simple: pregunta → respuesta con evidencia","Copilot que resume hallazgos"]',
 '["Solo busca en literatura científica (no web general)","20 búsquedas/mes en plan gratis","Puede no encontrar papers muy recientes","Solo en inglés"]',
 '[{"titulo":"Evidencia para informe PITM","descripcion":"¿Es el biosimilar de adalimumab tan eficaz como el original? Consensus muestra: SÍ (87% de los estudios apoyan no inferioridad). Adjuntas el resultado al informe.","dominio":"INVESTIGACION"},
   {"titulo":"Fundamentar protocolo PROA","descripcion":"¿La desescalada temprana de ATB en UCI reduce mortalidad? Consensus: SÍ (73% estudios). Lo usas para justificar el protocolo PROA del servicio.","dominio":"PROA"},
   {"titulo":"Evaluar nueva indicación off-label","descripcion":"¿Gabapentina es eficaz para prurito colestásico? Consensus analiza la evidencia y muestra grado de acuerdo de los estudios publicados.","dominio":"VALIDACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["evidencia","papers","consenso","PITM","off-label"]', 2),

('Elicit', 'https://elicit.com', '📚',
 'Asistente de revisiones sistemáticas, extrae datos de papers automáticamente',
 'Elicit automatiza partes de una revisión sistemática: busca papers relevantes, extrae datos (muestra, intervención, resultados, sesgo), y permite crear matrices de extracción de datos. Basado en modelos de lenguaje entrenados para ciencia.',
 'BUSQUEDA_CIENTIFICA', 'Elicit',
 'Gratis: 5.000 créditos, búsquedas, extracción básica',
 'Plus 10$/mes: más créditos, tablas de extracción, exportar CSV.',
 '["Automatiza extracción de datos de papers","Crea tablas de extracción personalizables","Ideal para revisiones sistemáticas","Encuentra papers relevantes con IA","Extrae diseño, muestra, resultados automáticamente"]',
 '["Créditos limitados en plan gratis","Solo papers en inglés (mayoritariamente)","No reemplaza revisión manual de calidad","Puede perder matices en la extracción"]',
 '[{"titulo":"Revisión sistemática para comisión","descripcion":"Comisión FyT pide revisar evidencia de 3 biosimilares de trastuzumab. Elicit encuentra 47 estudios, extrae datos de eficacia y seguridad en tabla comparativa automática.","dominio":"INVESTIGACION"},
   {"titulo":"Preparar sesión bibliográfica","descripcion":"Tema: IA en TDM. Elicit busca papers, extrae objetivo+método+conclusión de cada uno. En 1 hora tienes la base para la sesión.","dominio":"FORMACION"},
   {"titulo":"Evaluar calidad de estudios","descripcion":"Para un informe de posicionamiento: Elicit ayuda a clasificar los estudios por nivel de evidencia y riesgo de sesgo.","dominio":"INVESTIGACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["revisión sistemática","extracción datos","papers","comisión"]', 3),

('Semantic Scholar', 'https://semanticscholar.org', '🎓',
 'Motor académico con IA: TLDR, citas influyentes, grafos de citación',
 'Semantic Scholar de Allen Institute for AI es un motor de búsqueda académica que usa IA para generar resúmenes TLDR de papers, identificar citas influyentes, y crear grafos de citación. API gratuita integrada en SIGFAR Hub Radar IA.',
 'BUSQUEDA_CIENTIFICA', 'Allen Institute for AI',
 'Gratis: búsquedas ilimitadas, TLDR, API gratuita (100 req/5min)',
 'Gratis (financiado por Allen Institute).',
 '["TLDR: resumen de 1 línea de cada paper","Identifica citas más influyentes","Grafo visual de papers relacionados","API gratuita (integrada en Radar IA)","Alertas de nuevos papers por tema"]',
 '["Solo literatura científica","TLDR a veces impreciso","Cobertura menor que PubMed en biomedicina","Interfaz menos intuitiva"]',
 '[{"titulo":"Integrado en Radar IA","descripcion":"Semantic Scholar es una de las 4 fuentes del Radar IA de SIGFAR Hub. Escanea automáticamente papers sobre IA en farmacia hospitalaria.","dominio":"INVESTIGACION"},
   {"titulo":"Encontrar papers relacionados","descripcion":"Tienes un artículo clave sobre PROA con IA. Semantic Scholar muestra el grafo de papers que lo citan y que cita, descubriendo trabajos que no encontrarías en PubMed.","dominio":"INVESTIGACION"},
   {"titulo":"Alertas de nuevas publicaciones","descripcion":"Configura alertas para farmacia hospitalaria + inteligencia artificial. Cada semana recibes papers nuevos relevantes automáticamente.","dominio":"INVESTIGACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["papers","API","grafos","TLDR","Radar IA"]', 4),

('SciSpace', 'https://typeset.io', '📄',
 'Lee PDFs científicos con IA, explica párrafos, extrae tablas, chatbot sobre el paper',
 'SciSpace (antes Typeset) permite subir un PDF científico y chatear con él: explica párrafos complejos, extrae tablas como datos, resume secciones, y traduce. Ideal para leer papers densos rápidamente.',
 'BUSQUEDA_CIENTIFICA', 'SciSpace',
 'Gratis: 5 papers/día, chat sobre PDF, explicaciones',
 'Premium 12$/mes: ilimitado, múltiples PDFs, exportar.',
 '["Sube PDF y pregunta lo que quieras sobre él","Explica párrafos complejos en lenguaje simple","Extrae tablas como datos editables","Traduce secciones al español","Copilot de lectura científica"]',
 '["5 papers/día en plan gratis","Solo PDFs (no HTML de revistas)","A veces simplifica demasiado","Calidad depende del OCR del PDF"]',
 '[{"titulo":"Leer artículo complejo rápidamente","descripcion":"Paper de 15 páginas sobre farmacocinética poblacional de vancomicina. Subes el PDF y preguntas: ¿qué modelo PK usan? ¿qué covariables incluyen? Resumen en 2 minutos.","dominio":"FARMACOCINETICA"},
   {"titulo":"Extraer datos para meta-análisis","descripcion":"Subes 10 PDFs de estudios sobre biosimilares. SciSpace extrae automáticamente: n, intervención, comparador, outcome primario, resultado.","dominio":"INVESTIGACION"},
   {"titulo":"Preparar journal club","descripcion":"Sube el paper del journal club de esta semana. SciSpace resume introducción, métodos, resultados y limitaciones. Base para la presentación.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["PDF","papers","leer","extraer","traducir"]', 5),

('Scite', 'https://scite.ai', '🔬',
 'Muestra si un paper ha sido apoyado o contradicho por citas posteriores',
 'Scite analiza cómo ha sido citado un paper: apoyo, contradicción o mención neutral. Útil para evaluar si las conclusiones de un estudio siguen siendo válidas o han sido refutadas por estudios posteriores.',
 'BUSQUEDA_CIENTIFICA', 'Scite',
 'Gratis: búsquedas limitadas, Smart Citations básicas',
 'Premium 15$/mes: ilimitado, dashboards, extensión navegador.',
 '["Smart Citations: apoyado/contradicho/mencionado","Evalúa vigencia de conclusiones","Extensión de navegador para PubMed","Dashboard de citación por paper"]',
 '["Plan gratis limitado","Cobertura biomédica menor que PubMed","Clasificación apoyo/contradicción no siempre exacta"]',
 '[{"titulo":"Evaluar vigencia de un protocolo","descripcion":"Tu protocolo de vancomicina se basa en un paper de 2018. Scite muestra que 3 estudios posteriores apoyan sus conclusiones pero 1 las contradice. ¿Hay que actualizar?","dominio":"VALIDACION"},
   {"titulo":"Fundamentar informe con evidencia sólida","descripcion":"Para el informe PITM: verifica que los papers que citas no han sido contradichos. Scite te da confianza en la evidencia que presentas.","dominio":"INVESTIGACION"},
   {"titulo":"Detectar controversias científicas","descripcion":"¿Hay consenso sobre el target AUC/MIC de vancomicina 400-600? Scite muestra los papers que apoyan vs los que proponen targets diferentes.","dominio":"FARMACOCINETICA"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["citas","apoyo","contradicción","evidencia","vigencia"]', 6),

('OpenEvidence', 'https://openevidence.com', '🏥',
 'Preguntas clínicas → respuestas basadas en evidencia con citas de trials',
 'OpenEvidence está diseñado específicamente para profesionales sanitarios. Responde preguntas clínicas con evidencia de ensayos clínicos y guías. Cada respuesta incluye citas con links a los papers originales.',
 'BUSQUEDA_CIENTIFICA', 'OpenEvidence',
 'Gratis: preguntas ilimitadas, citas, evidencia clínica',
 'Gratis (financiado por inversores).',
 '["Diseñado para profesionales sanitarios","Cita ensayos clínicos y guías directamente","Respuestas estructuradas con niveles de evidencia","Gratis e ilimitado","Actualizado con evidencia reciente"]',
 '["Solo en inglés","Menos versátil que ChatGPT para tareas no clínicas","No permite subir documentos propios","Cobertura farmacéutica menos profunda que clínica"]',
 '[{"titulo":"Consulta point-of-care","descripcion":"Médico pregunta: ¿vancomicina o linezolid para neumonía por MRSA en UCI? OpenEvidence compara evidencia de trials con recomendaciones IDSA.","dominio":"PROA"},
   {"titulo":"Dosis en poblaciones especiales","descripcion":"¿Dosis de enoxaparina en obesidad mórbida (IMC >40)? OpenEvidence busca evidencia de estudios PK en obesos y genera recomendación.","dominio":"VALIDACION"},
   {"titulo":"Evidencia para protocolo","descripcion":"Estás elaborando protocolo de profilaxis ATB quirúrgica. OpenEvidence recopila evidencia por tipo de cirugía con citas.","dominio":"PROA"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["clínica","evidencia","trials","point-of-care","guías"]', 7),

('Connected Papers', 'https://connectedpapers.com', '🕸️',
 'Grafo visual de papers relacionados a partir de un artículo semilla',
 'Connected Papers genera un grafo visual interactivo de papers relacionados con un artículo semilla. Los nodos más cercanos son los más similares. Ideal para descubrir papers que no encontrarías con búsquedas convencionales.',
 'BUSQUEDA_CIENTIFICA', 'Connected Papers',
 'Gratis: 5 grafos/mes, exploración visual',
 'Academic 5$/mes: grafos ilimitados, exportar, alertas.',
 '["Grafo visual interactivo de papers","Descubre papers que no encontrarías buscando","Muestra conexiones temáticas","Fácil de usar: pega DOI o título"]',
 '["5 grafos/mes en plan gratis","Solo muestra papers similares, no toda la literatura","No analiza contenido de los papers","Sesgado hacia papers muy citados"]',
 '[{"titulo":"Explorar campo de investigación nuevo","descripcion":"Empiezas a investigar IA en PROA. Introduces el paper seminal de Rawson et al. y Connected Papers te muestra 40 papers relacionados que no conocías.","dominio":"INVESTIGACION"},
   {"titulo":"Completar bibliografía de artículo","descripcion":"Escribiendo un artículo sobre IA en farmacia hospitalaria. Introduces tu referencia principal y descubres 10 papers recientes que deberías citar.","dominio":"INVESTIGACION"},
   {"titulo":"Preparar revisión bibliográfica","descripcion":"Para la memoria de la rotación FIR: genera el grafo de tu tema y descubre la estructura del campo de investigación.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["grafos","papers","bibliografía","exploración"]', 8),

('Litmaps', 'https://litmaps.com', '🗺️',
 'Mapas de literatura: descubre papers conectados cronológicamente',
 'Litmaps crea mapas cronológicos de literatura científica mostrando cómo evolucionan las ideas en el tiempo. Muestra cadenas de citación y permite descubrir papers semilla y papers recientes de un campo.',
 'BUSQUEDA_CIENTIFICA', 'Litmaps',
 'Gratis: 1 mapa, exploración básica',
 'Starter 10$/mes: mapas ilimitados, alertas, colaboración.',
 '["Mapa cronológico de evolución del campo","Cadenas de citación visuales","Descubre papers semilla y últimos avances","Alertas de nuevos papers"]',
 '["1 mapa gratis muy limitado","Interfaz puede ser confusa al inicio","Menos papers que PubMed"]',
 '[{"titulo":"Evolución del TDM con IA","descripcion":"Crea mapa de TDM + machine learning: ves cómo el campo evolucionó de regresión lineal (2010) a redes neuronales (2020) a MAP bayesiano con IA (2024).","dominio":"FARMACOCINETICA"},
   {"titulo":"Rastrear origen de una idea","descripcion":"¿De dónde viene el concepto de PROA con IA? Litmaps muestra los papers fundacionales y cómo se ramificó en antimicrobial stewardship + ML.","dominio":"PROA"},
   {"titulo":"Vigilancia bibliográfica","descripcion":"Configura alertas para tu mapa de IA en farmacia hospitalaria. Cada semana recibes papers nuevos que se conectan con tu mapa.","dominio":"INVESTIGACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["mapas","cronología","citaciones","evolución"]', 9),

('PubMed AI', 'https://pubmed.ncbi.nlm.nih.gov', '📖',
 'PubMed con resúmenes IA integrados en resultados de búsqueda',
 'PubMed está integrando funcionalidades de IA: resúmenes generados automáticamente, clasificación por relevancia mejorada, y asistente de búsqueda. Es la base de datos de referencia en biomedicina con 35 millones de artículos.',
 'BUSQUEDA_CIENTIFICA', 'NCBI/NLM',
 'Gratis: búsquedas ilimitadas, abstracts, API eUtils',
 'Gratis (financiado por NIH).',
 '["35M artículos biomédicos","API gratuita (eUtils) integrada en Radar IA","Referencia estándar en biomedicina","Filtros avanzados: MeSH, fechas, tipos estudio","Resúmenes IA en desarrollo"]',
 '["Interfaz antigua y poco intuitiva","Búsqueda requiere conocer operadores booleanos","No analiza contenido: solo busca","Muchos papers de pago sin acceso completo"]',
 '[{"titulo":"Integrado en Radar IA y P15","descripcion":"PubMed es fuente principal del Radar IA de SIGFAR Hub. También integrado en el chat de P15: al preguntar sobre un fármaco, busca automáticamente en PubMed.","dominio":"INVESTIGACION"},
   {"titulo":"Búsqueda para informes PITM","descripcion":"Informe de posicionamiento terapéutico: busca ensayos clínicos fase III del nuevo fármaco con filtros MeSH + Clinical Trial + últimos 5 años.","dominio":"INVESTIGACION"},
   {"titulo":"Alertas por email","descripcion":"Configura My NCBI para recibir alertas semanales de nuevos papers sobre tus temas: vancomicina TDM, PROA IA, nutrición artificial IA.","dominio":"INVESTIGACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["PubMed","papers","biomedicina","API","Radar IA"]', 10),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 3: GESTION_DOCUMENTAL (3 herramientas)
-- ═══════════════════════════════════════════════════════════════

('NotebookLM', 'https://notebooklm.google.com', '📓',
 'Sube PDFs, solo responde desde TUS documentos (0 alucinaciones), genera podcasts',
 'NotebookLM de Google permite subir hasta 50 documentos y chatear exclusivamente con ellos. A diferencia de ChatGPT, SOLO responde desde tus documentos, eliminando alucinaciones. Genera podcasts de audio donde dos voces discuten tus documentos.',
 'GESTION_DOCUMENTAL', 'Google',
 'Gratis: 100 notebooks, 50 fuentes/notebook, podcasts audio',
 'NotebookLM Plus (próximamente): más fuentes, audio avanzado.',
 '["0 alucinaciones: solo responde desde tus documentos","Genera podcasts de audio (2 voces discuten el contenido)","Gratis y sin límites prácticos","50 PDFs por notebook","Citas exactas del documento fuente"]',
 '["Solo Google account","No permite editar fuentes una vez subidas","Sin API","Calidad audio solo buena en inglés","No procesa imágenes dentro de PDFs"]',
 '[{"titulo":"Consultar guías ESPEN/ASPEN/SENPE","descripcion":"Sube las 5 guías de nutrición parenteral al notebook. Pregunta: ¿cuándo iniciar NP en paciente crítico con íleo? Responde con citas exactas de TUS guías, sin inventar.","dominio":"NUTRICION"},
   {"titulo":"Protocolo PROA interno","descripcion":"Sube protocolo PROA del CHGUV + guía IDSA + EUCAST breakpoints. Pregunta: ¿tratamiento empírico ITU nosocomial en paciente alérgico a penicilina? Responde solo desde tus documentos.","dominio":"PROA"},
   {"titulo":"Formación residentes con podcast","descripcion":"Sube 10 artículos sobre vancomicina TDM. NotebookLM genera podcast de 15 min donde 2 voces discuten los hallazgos. El R1 lo escucha en el coche camino al hospital.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_CON_DPA', TRUE,
 '["documentos","guías","0 alucinaciones","podcast","RAG"]', 1),

('ChatGPT Projects', 'https://chat.openai.com', '📁',
 'Sube ficheros a un Project y ChatGPT responde solo desde ellos',
 'ChatGPT Projects permite crear proyectos con documentos subidos como contexto. ChatGPT usa esos documentos como fuente principal, reduciendo alucinaciones. Permite instrucciones personalizadas por proyecto.',
 'GESTION_DOCUMENTAL', 'OpenAI',
 'Gratis limitado en GPT-4o mini. Plus para Projects completos.',
 'Plus 20$/mes: Projects con GPT-4o, documentos grandes.',
 '["Instrucciones personalizadas por proyecto","Combina documentos con capacidades generales de GPT-4","Puede generar nuevo contenido basado en tus docs","Más flexible que NotebookLM (no solo RAG)"]',
 '["Requiere Plus para funcionalidad completa","Puede mezclar conocimiento propio con tus docs","Menos estricto que NotebookLM en solo usar tus fuentes","Límite de archivos por proyecto"]',
 '[{"titulo":"PNTs del servicio","descripcion":"Sube todos los PNTs del servicio a un Project. Pregunta: ¿cuál es el procedimiento para gestionar una alerta de medicamento falsificado? Responde desde tus PNTs.","dominio":"GESTION"},
   {"titulo":"Analizar normativa","descripcion":"Sube el RD de prescripción enfermera + normativa de Conselleria. Pregunta: ¿puede la enfermera de UCI modificar velocidad de perfusión de noradrenalina? Responde con artículos exactos.","dominio":"GESTION"},
   {"titulo":"Comparar fichas técnicas","descripcion":"Sube las fichas técnicas de 3 ISRS y pide: compara indicaciones, interacciones con warfarina, uso en embarazo y precio. Genera tabla comparativa.","dominio":"VALIDACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["documentos","Projects","PNTs","normativa","fichas técnicas"]', 2),

('Claude Projects', 'https://claude.ai', '📂',
 'Documentos como contexto con 200K tokens y Artifacts para resultados editables',
 'Claude Projects funciona similar a ChatGPT Projects pero con 200K tokens de contexto (puede procesar documentos mucho más largos) y genera Artifacts editables como salida (documentos, código, tablas).',
 'GESTION_DOCUMENTAL', 'Anthropic',
 'Pro necesario para Projects completos.',
 'Pro 20$/mes: Projects con Claude Opus, 200K contexto.',
 '["200K tokens: procesa documentos enormes","Artifacts: genera documentos editables","Razonamiento más profundo que GPT-4 en análisis","Excelente para documentos técnicos complejos"]',
 '["Requiere Pro para Projects","Sin generación de audio (vs NotebookLM)","Menos plugins que ChatGPT","Límites de uso diario en plan Pro"]',
 '[{"titulo":"Analizar guías extensas completas","descripcion":"Sube la guía IDSA 2023 completa de tratamiento antimicrobiano (200 páginas). Claude la procesa ENTERA gracias a 200K contexto. Pregunta sobre cualquier sección.","dominio":"PROA"},
   {"titulo":"Generar protocolos desde múltiples fuentes","descripcion":"Sube guía ESPEN + protocolo actual del CHGUV + últimos 5 papers sobre NP en UCI. Claude genera borrador de protocolo actualizado como Artifact editable.","dominio":"NUTRICION"},
   {"titulo":"Análisis farmacoeconómico","descripcion":"Sube datos de consumos del servicio + precios SNS + informe de biosimilares. Claude analiza oportunidades de ahorro y genera informe con tablas y recomendaciones.","dominio":"GESTION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["documentos","200K contexto","Artifacts","guías extensas"]', 3),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 4: PRESENTACIONES (5 herramientas)
-- ═══════════════════════════════════════════════════════════════

('Gamma', 'https://gamma.app', '🎨',
 'Prompt → presentación profesional completa en 2 minutos con diseño e imágenes',
 'Gamma genera presentaciones, documentos y páginas web profesionales desde un simple prompt. Incluye diseño automático, imágenes relevantes, y permite edición posterior. Ideal para preparar presentaciones rápidamente.',
 'PRESENTACIONES', 'Gamma',
 'Gratis: 10 presentaciones, diseño AI, exportar PDF',
 'Plus 10$/mes: ilimitado, sin marca de agua, exportar PPT.',
 '["Genera presentación completa en 2 minutos","Diseño profesional automático","Imágenes relevantes integradas","Edición posterior fácil","Exporta a PDF y PPT"]',
 '["Marca de agua en plan gratis","Diseños a veces genéricos","Sin animaciones complejas","Imágenes no siempre relevantes al contexto clínico"]',
 '[{"titulo":"Sesión de servicio semanal","descripcion":"Escribe: genera presentación sobre resultados del programa PROA del último mes: 45 intervenciones, 78% aceptación, ahorro 12.000€. Gamma crea 10 slides profesionales.","dominio":"COMUNICACION"},
   {"titulo":"Ponencia para congreso SEFH","descripcion":"Prompt: presentación de 15 min sobre IA en farmacia hospitalaria: experiencia SIGFAR Hub. Genera estructura con diapositivas de introducción, métodos, resultados, conclusiones.","dominio":"COMUNICACION"},
   {"titulo":"Material formativo para residentes","descripcion":"Genera presentación sobre farmacocinética de vancomicina: modelo bicompartimental, parámetros PK, monitorización AUC/MIC, ajuste bayesiano. Con gráficos y esquemas.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["presentaciones","diseño","rápido","sesiones","congresos"]', 1),

('Napkin AI', 'https://napkin.ai', '📐',
 'Convierte texto en diagramas y visualizaciones automáticamente',
 'Napkin AI convierte texto plano en diagramas profesionales: flowcharts, organigramas, mapas mentales, líneas de tiempo. Pegás tu texto y genera visualización instantánea.',
 'PRESENTACIONES', 'Napkin AI',
 'Gratis: diagramas ilimitados, exportar PNG/SVG',
 'Pro (próximamente): más estilos, exportar editables.',
 '["Texto → diagrama en segundos","Múltiples tipos: flowcharts, organigramas, mapas mentales","Exportar PNG/SVG","Muy fácil de usar"]',
 '["Estilos limitados en plan gratis","No edita diagramas existentes","Sin integración con presentaciones","Diagramas a veces simplificados"]',
 '[{"titulo":"Diagrama de flujo PROA","descripcion":"Pega el protocolo PROA en texto: si cultivo positivo y ATB empírico amplio espectro → evaluar desescalada → si sensible a amoxicilina-clav → switch. Napkin genera flowchart profesional.","dominio":"PROA"},
   {"titulo":"Algoritmo de dosificación","descripcion":"Pega el algoritmo de TDM de vancomicina en texto. Napkin genera diagrama de flujo visual: primer nivel → carga vs no carga → mantenim → TDM día 3 → ajuste.","dominio":"FARMACOCINETICA"},
   {"titulo":"Orgánigrama del servicio","descripcion":"Lista el personal del servicio con roles. Napkin genera organigrama profesional para la memoria anual.","dominio":"GESTION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["diagramas","flowcharts","visual","texto-a-diagrama"]', 2),

('Beautiful.ai', 'https://beautiful.ai', '✨',
 'Presentaciones con diseño adaptativo inteligente que se ajusta automáticamente',
 'Beautiful.ai genera presentaciones con un motor de diseño que adapta automáticamente el layout al contenido. Los slides siempre quedan profesionales sin esfuerzo de diseño.',
 'PRESENTACIONES', 'Beautiful.ai',
 'Gratis: limitado. Pro 12$/mes: ilimitado, exportar PPT.',
 'Pro 12$/mes: presentaciones ilimitadas, exportar, plantillas premium.',
 '["Diseño adaptativo automático","Siempre queda profesional","Plantillas modernas","Exporta a PowerPoint"]',
 '["Plan gratis muy limitado","Menos flexibilidad que PowerPoint","Sin IA generativa de contenido","Requiere cuenta de pago para uso real"]',
 '[{"titulo":"Informe trimestral para dirección","descripcion":"Presenta los KPIs del servicio con gráficos profesionales: intervenciones, ahorro, cobertura validación. Beautiful.ai ajusta el diseño automáticamente.","dominio":"GESTION"},
   {"titulo":"Poster para congreso","descripcion":"Diseño adaptativo para crear poster A0 con los resultados del estudio PROA. Layout profesional automático.","dominio":"COMUNICACION"},
   {"titulo":"Material onboarding residentes","descripcion":"Presentación de bienvenida para nuevos residentes: estructura del servicio, protocolos, herramientas, rotaciones. Diseño profesional sin esfuerzo.","dominio":"FORMACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["presentaciones","diseño","profesional","automático"]', 3),

('Canva', 'https://canva.com', '🎭',
 'Diseño gráfico con IA: posters, infografías, vídeos, presentaciones',
 'Canva es la herramienta de diseño más popular con integración de IA. Permite crear posters, infografías, presentaciones, vídeos, logos y más. Magic Write genera texto, Magic Design genera diseños completos desde prompts.',
 'PRESENTACIONES', 'Canva',
 'Gratis: diseño básico, plantillas, Magic Write limitado',
 'Pro 120€/año: Magic Design, marca kit, fondos removidos, 1TB.',
 '["Todo-en-uno: presentaciones, posters, infografías, vídeos","Miles de plantillas profesionales","Magic Write: genera texto con IA","Magic Design: diseño desde prompt","Colaboración en tiempo real","Exporta en todos los formatos"]',
 '["Plan gratuito limitado en funciones IA","Puede parecer poco profesional si usas plantillas estándar","Curva de aprendizaje para funciones avanzadas"]',
 '[{"titulo":"Poster para congreso SEFH","descripcion":"Selecciona plantilla poster científico A0. Añade datos de tu estudio. Canva ajusta diseño, gráficos, bibliografía. Exporta PDF para imprimir.","dominio":"COMUNICACION"},
   {"titulo":"Infografía protocolo para enfermería","descripcion":"Crea infografía visual del protocolo de administración de vancomicina: dilución, velocidad, monitorización. Imprime y coloca en la unidad.","dominio":"FORMACION"},
   {"titulo":"Vídeo formativo para residentes","descripcion":"Crea vídeo de 3 minutos explicando el cálculo de AUC bayesiano con animaciones. Magic Media genera las animaciones desde texto.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_CON_DPA', TRUE,
 '["diseño","posters","infografías","vídeos","presentaciones"]', 4),

('Sider', 'https://sider.ai', '🔗',
 'Extensión de navegador: resume, traduce, reescribe cualquier página web con IA',
 'Sider es una extensión de navegador que añade IA a cualquier página web. Selecciona texto y Sider lo resume, traduce, explica o reescribe. Funciona sobre PubMed, UpToDate, fichas técnicas, etc.',
 'PRESENTACIONES', 'Sider',
 'Gratis: 30 consultas/día, resumen, traducción',
 'Pro 10$/mes: ilimitado, GPT-4, Claude, múltiples modelos.',
 '["Funciona sobre CUALQUIER página web","Resume, traduce, explica seleccionando texto","Integración directa en navegador","Múltiples modelos (GPT-4, Claude)"]',
 '["30 consultas/día en plan gratis","Requiere extensión de navegador","Privacidad: envía texto seleccionado al cloud","No funciona en PDFs offline"]',
 '[{"titulo":"Leer abstracts de PubMed en español","descripcion":"Busca en PubMed. Selecciona abstract en inglés. Clic derecho → Sider → Traducir al español. Listo en 3 segundos.","dominio":"INVESTIGACION"},
   {"titulo":"Resumir ficha técnica larga","descripcion":"Abre la ficha técnica de un fármaco en CIMA. Selecciona sección de interacciones (3 páginas). Sider → Resume en 5 puntos clave.","dominio":"VALIDACION"},
   {"titulo":"Explicar artículo complejo","descripcion":"Paper técnico sobre farmacocinética poblacional. Selecciona párrafo de métodos. Sider → Explícame esto como si fuera un R1.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["extensión","navegador","resumir","traducir","PubMed"]', 5),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 5: ESCRITURA (5 herramientas)
-- ═══════════════════════════════════════════════════════════════

('ChatGPT Canvas', 'https://chat.openai.com', '🖊️',
 'Editor visual donde escribes y la IA edita en tiempo real',
 'Canvas de ChatGPT es un editor visual colaborativo donde tú escribes y la IA edita: reescribe, acorta, amplía, ajusta tono, traduce, añade citas. Ideal para escritura científica iterativa.',
 'ESCRITURA', 'OpenAI',
 'Gratis con GPT-4o mini, Canvas básico',
 'Plus 20$/mes: Canvas con GPT-4o, edición avanzada.',
 '["Editor visual intuitivo","IA edita en tiempo real","Ajusta tono: formal, científico, divulgativo","Traduce manteniendo formato","Acorta o amplía texto con un clic"]',
 '["Requiere Plus para GPT-4o","Solo dentro de ChatGPT","Sin colaboración multi-usuario","No exporta a Word directamente"]',
 '[{"titulo":"Escribir artículo para Farm Hosp","descripcion":"Escribe borrador de introducción. Pide a Canvas: hazlo más formal y científico, añade 3 citas recientes. Canvas reescribe manteniendo tu estructura.","dominio":"INVESTIGACION"},
   {"titulo":"Acortar abstract a 250 palabras","descripcion":"Tu abstract tiene 400 palabras. Canvas → Acortar a 250. Revisa que no pierda información clave. Ajusta. Listo.","dominio":"INVESTIGACION"},
   {"titulo":"Adaptar comunicación para pacientes","descripcion":"Tienes una hoja informativa técnica sobre warfarina. Canvas → Reescribe en lenguaje comprensible para pacientes. Nivel lectura: 6º primaria.","dominio":"COMUNICACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["escritura","edición","artículos","abstracts","redacción"]', 1),

('Grammarly', 'https://grammarly.com', '📝',
 'Corrector ortográfico y de estilo con IA, ideal para artículos en inglés',
 'Grammarly corrige gramática, ortografía, puntuación y estilo en inglés. La versión IA sugiere reescrituras completas, ajusta tono y mejora claridad. Esencial para publicar en revistas internacionales.',
 'ESCRITURA', 'Grammarly',
 'Gratis: corrección básica gramática/ortografía',
 'Premium 12$/mes: correcciones avanzadas, tono, plagio, reescritura IA.',
 '["Corrección en tiempo real en cualquier app","Sugiere reescrituras para mejorar claridad","Detecta plagio","Ajusta tono: académico, profesional, casual","Extensión de navegador + Word + Google Docs"]',
 '["Solo en inglés (limitado en español)","Premium caro para uso individual","Puede sobre-corregir estilo personal","Envía texto a servidores Grammarly"]',
 '[{"titulo":"Revisar artículo antes de enviar a revista","descripcion":"Pegas el manuscrito en inglés. Grammarly corrige gramática, sugiere mejoras de estilo científico, y verifica que no hay plagio involuntario.","dominio":"INVESTIGACION"},
   {"titulo":"Escribir emails profesionales en inglés","descripcion":"Email a colaborador internacional sobre el proyecto multi-centro. Grammarly ajusta tono profesional y corrige errores.","dominio":"COMUNICACION"},
   {"titulo":"Mejorar abstract para congreso","descripcion":"Abstract de 250 palabras en inglés. Grammarly sugiere verbos más activos, elimina redundancias, mejora flow.","dominio":"INVESTIGACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["corrección","inglés","gramática","estilo","plagio"]', 2),

('DeepL Write', 'https://deepl.com/write', '🌍',
 'Traducción y reescritura superior a Google Translate, ideal para español-inglés',
 'DeepL Write no solo traduce, sino que reescribe textos mejorando estilo, gramática y claridad. Considerado el mejor traductor para pares de idiomas europeos, especialmente español-inglés.',
 'ESCRITURA', 'DeepL',
 'Gratis: traducción ilimitada, Write limitado, 1500 caracteres/vez',
 'Pro 25€/mes: textos ilimitados, 500K caracteres, API, documentos completos.',
 '["Mejor traducción español↔inglés del mercado","Write mejora estilo además de traducir","Mantiene formato y estructura","Traducción de documentos completos (PDF, DOCX)"]',
 '["Write limitado en plan gratis","No genera contenido nuevo, solo traduce/reescribe","Sin modo especializado para textos médicos","Archivos grandes requieren Pro"]',
 '[{"titulo":"Traducir artículo a inglés para publicar","descripcion":"Escribe el artículo en español. DeepL traduce manteniendo la estructura científica, terminología técnica y formato de citas. Revisas y ajustas matices.","dominio":"INVESTIGACION"},
   {"titulo":"Traducir abstract para congreso","descripcion":"Abstract en español → DeepL → inglés científico de alta calidad. Mucho mejor que Google Translate para terminología farmacéutica.","dominio":"INVESTIGACION"},
   {"titulo":"Leer guidelines en inglés","descripcion":"Guía IDSA de 50 páginas en inglés. DeepL traduce el PDF completo a español manteniendo tablas y formato. Lectura mucho más rápida.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["traducción","español","inglés","DeepL","artículos"]', 3),

('QuillBot', 'https://quillbot.com', '🪶',
 'Parafraseo inteligente para evitar plagio en revisiones',
 'QuillBot parafrasea texto manteniendo el significado pero cambiando la redacción. Múltiples modos: fluido, formal, simple, creativo. Útil para evitar plagio involuntario en revisiones bibliográficas.',
 'ESCRITURA', 'QuillBot',
 'Gratis: parafraseo básico, 125 palabras/vez, 2 modos',
 'Premium 10$/mes: ilimitado, 7 modos, comparador, resumidor.',
 '["7 modos de parafraseo diferentes","Detector de plagio integrado","Resumidor de textos","Extensión para Chrome y Word"]',
 '["125 palabras/vez en plan gratis","Puede alterar significado técnico al parafrasear","Solo en inglés (español limitado)","No entiende contexto clínico específico"]',
 '[{"titulo":"Parafrasear para revisión bibliográfica","descripcion":"Copias conclusiones de 10 papers para tu revisión. QuillBot parafrasea cada una manteniendo el significado pero con tus palabras. Sin plagio.","dominio":"INVESTIGACION"},
   {"titulo":"Simplificar texto técnico","descripcion":"Párrafo técnico sobre PK poblacional → QuillBot modo Simple → versión comprensible para residentes de primer año.","dominio":"FORMACION"},
   {"titulo":"Reescribir introducción de artículo","descripcion":"La introducción suena muy similar a otro paper. QuillBot la reescribe manteniendo las ideas pero con redacción original.","dominio":"INVESTIGACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["parafraseo","plagio","reescritura","revisión"]', 4),

('Writefull', 'https://writefull.com', '🎯',
 'Corrector específico para escritura académica y científica',
 'Writefull está entrenado específicamente para escritura académica. Corrige errores comunes en papers, sugiere vocabulario científico apropiado, y verifica que frases son idiomáticas en inglés académico.',
 'ESCRITURA', 'Writefull',
 'Gratis: correcciones básicas, widget Overleaf',
 'Premium 5€/mes: correcciones avanzadas, parafraseo, abstracter.',
 '["Especializado en escritura académica","Entrenado con millones de papers publicados","Widget para Overleaf (LaTeX)","Abstracter: genera abstract desde paper","Vocabulario científico correcto"]',
 '["Solo para textos académicos en inglés","Plan gratis limitado","Interfaz menos pulida que Grammarly","No tan útil para textos no científicos"]',
 '[{"titulo":"Corregir inglés académico de manuscrito","descripcion":"Pegas tu paper. Writefull corrige no solo gramática sino vocabulario científico: significantly → markedly, we did → we performed. Más publicable.","dominio":"INVESTIGACION"},
   {"titulo":"Generar abstract automáticamente","descripcion":"Escribes el paper completo. Writefull Abstracter genera abstract estructurado (Objective, Methods, Results, Conclusions) de 250 palabras.","dominio":"INVESTIGACION"},
   {"titulo":"Mejorar estilo académico","descripcion":"Revisas el manuscrito antes de enviar. Writefull sugiere: en vez de a lot of → numerous, because of → owing to. Estilo más formal y publicable.","dominio":"INVESTIGACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["académico","papers","corrección","Overleaf","científico"]', 5),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 6: DESARROLLO (10 herramientas)
-- ═══════════════════════════════════════════════════════════════

('Claude Code', 'https://claude.ai/code', '💻',
 'Terminal de código agéntico: programas hablando en español, crea apps completas',
 'Claude Code es un agente de programación que ejecuta directamente en terminal. Le dices lo que necesitas en español y genera, ejecuta y depura código automáticamente. Creó SIGFAR Hub completo.',
 'DESARROLLO', 'Anthropic',
 'Incluido en Claude Max (100$/mes). API por tokens.',
 'Max 100$/mes. API: $15/M input, $75/M output (Opus).',
 '["Programas hablando en español","Crea aplicaciones completas (frontend+backend+DB)","Ejecuta y depura código directamente","Comprende contexto del proyecto completo","Creó SIGFAR Hub (3500+ líneas Python + 3800+ líneas React)"]',
 '["Costoso (Max 100$/mes o API)","Requiere conocimientos básicos de programación para supervisar","Solo funciona en terminal","Puede cometer errores que hay que revisar"]',
 '[{"titulo":"Creación de SIGFAR Hub","descripcion":"Claude Code creó todo SIGFAR Hub: 100 endpoints FastAPI, 3800 líneas React, 27 tablas PostgreSQL, 8 módulos completos, hablando en español. Coste total: ~15€.","dominio":"DESARROLLO"},
   {"titulo":"Automatizar extracción de datos","descripcion":"Necesitas extraer datos de ICCA a CSV diariamente. Le dices a Claude Code: crea un script Python que se conecte via ORDS, extraiga pacientes activos, y genere CSV. Lo hace en 5 minutos.","dominio":"DESARROLLO"},
   {"titulo":"Crear calculadora clínica web","descripcion":"Le pides: crea una calculadora web de Cockcroft-Gault + ajuste de vancomicina con interfaz bonita. Genera HTML+CSS+JS funcional en 2 minutos.","dominio":"DESARROLLO"}]',
 'AVANZADO', 'CLOUD_ANONIMIZAR', TRUE,
 '["programación","agente","terminal","Python","React","SIGFAR Hub"]', 1),

('Cursor', 'https://cursor.com', '🖱️',
 'IDE con IA integrada: escribe código con asistencia en cada línea',
 'Cursor es un editor de código (basado en VS Code) con IA integrada en cada aspecto: autocompletado, chat sobre el código, refactoring, generación de tests. Soporta GPT-4, Claude, y modelos locales.',
 'DESARROLLO', 'Cursor Inc.',
 'Gratis: autocompletado básico, 2000 sugerencias/mes',
 'Pro 20$/mes: ilimitado, GPT-4, Claude, chat sobre codebase.',
 '["IDE completo con IA nativa","Autocompletado inteligente contextual","Chat sobre tu código (entiende el proyecto)","Soporta múltiples modelos (GPT-4, Claude)","Basado en VS Code (familiar)"]',
 '["Plan gratis limitado","Requiere suscripción para uso serio","Puede sugerir código inseguro","Necesita buen hardware para funcionar fluido"]',
 '[{"titulo":"Desarrollar módulos de SIGFAR Hub","descripcion":"Abres el proyecto en Cursor. Pides: añade un endpoint que calcule AUC bayesiana de vancomicina con los datos del paciente. Genera código Python correcto.","dominio":"DESARROLLO"},
   {"titulo":"Refactorizar código legacy","descripcion":"Tienes un script PL/SQL de 500 líneas en APEX. Cursor lo convierte a Python + FastAPI manteniendo la lógica, con tests automáticos.","dominio":"DESARROLLO"},
   {"titulo":"Crear tests automáticos","descripcion":"Selecciona una función. Cursor genera suite de tests con pytest cubriendo casos normales, edge cases y errores esperados.","dominio":"DESARROLLO"}]',
 'AVANZADO', 'CLOUD_ANONIMIZAR', TRUE,
 '["IDE","código","autocompletado","VS Code","desarrollo"]', 2),

('GitHub Copilot', 'https://github.com/features/copilot', '🤖',
 'Autocompletado inteligente de código en VS Code',
 'GitHub Copilot sugiere código mientras escribes en VS Code. Entiende comentarios y genera funciones completas. Integrado con GitHub para context de repositorios.',
 'DESARROLLO', 'GitHub/Microsoft',
 'Gratis para estudiantes y open-source. Copilot Free: 2000 sugerencias/mes.',
 'Individual 10$/mes, Business 19$/usuario/mes.',
 '["Autocompletado predictivo excelente","Entiende comentarios en español","Chat integrado en VS Code","Genera funciones completas desde docstrings"]',
 '["Requiere suscripción","Sugerencias a veces incorrectas","Menos capaz que Claude Code para tareas complejas","Solo IDE (no agéntico)"]',
 '[{"titulo":"Autocompletar queries SQL","descripcion":"Escribes -- Obtener pacientes con vancomicina y creatinina > 1.5. Copilot genera el SELECT completo con JOINs correctos.","dominio":"DESARROLLO"},
   {"titulo":"Generar funciones desde comentarios","descripcion":"# Calcular AUC bayesiana con 2 niveles. Copilot genera la función Python completa con modelo bicompartimental.","dominio":"DESARROLLO"},
   {"titulo":"Escribir documentación","descripcion":"Selecciona función → Copilot genera docstring con parámetros, retorno, ejemplo de uso y excepciones.","dominio":"DESARROLLO"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["autocompletado","VS Code","GitHub","código"]', 3),

('Bolt.new', 'https://bolt.new', '⚡',
 'Describe una app → genera código completo desplegable en el navegador',
 'Bolt.new genera aplicaciones web completas desde una descripción en lenguaje natural. Incluye frontend, backend, y despliegue. Todo en el navegador, sin instalar nada.',
 'DESARROLLO', 'StackBlitz',
 'Gratis: 10 generaciones/día, preview en navegador',
 'Pro 20$/mes: generaciones ilimitadas, deploy a producción.',
 '["App completa desde descripción","Sin instalar nada (todo en navegador)","Deploy inmediato","Preview en tiempo real"]',
 '["Apps simples, no para proyectos grandes","Plan gratis limitado","Código generado puede ser difícil de mantener","Sin bases de datos complejas"]',
 '[{"titulo":"Prototipo de calculadora clínica","descripcion":"Escribe: crea calculadora de Cockcroft-Gault con campos de edad, peso, creatinina, sexo, y que muestre resultado con recomendación de ajuste. Lista en 1 minuto.","dominio":"DESARROLLO"},
   {"titulo":"Dashboard rápido de datos","descripcion":"Necesitas mostrar datos de consumo a la directora. Bolt genera dashboard con gráficos desde JSON en 2 minutos.","dominio":"GESTION"},
   {"titulo":"Formulario de recogida de datos","descripcion":"Necesitas formulario para estudio observacional. Bolt genera form con validación, almacenamiento y exportar CSV.","dominio":"INVESTIGACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["no-code","prototipo","rápido","web","navegador"]', 4),

('Lovable', 'https://lovable.dev', '💗',
 'Similar a Bolt, orientado a apps con diseño bonito en React',
 'Lovable genera aplicaciones web con diseño profesional y moderno. Enfocado en la estética y experiencia de usuario. Genera código React + Tailwind CSS de alta calidad.',
 'DESARROLLO', 'Lovable',
 'Gratis: 5 generaciones/día, preview',
 'Pro 20$/mes: ilimitado, deploy, custom domains.',
 '["Diseño automático profesional","Genera React + Tailwind","Apps estéticamente bonitas","Iteración con prompts"]',
 '["Plan gratis limitado","Solo para apps web simples","Código difícil de customizar","Sin backend complejo"]',
 '[{"titulo":"Landing page del servicio","descripcion":"Crea página web del Servicio de Farmacia del CHGUV con: equipo, publicaciones, líneas de investigación, contacto. Diseño moderno.","dominio":"COMUNICACION"},
   {"titulo":"Panel de indicadores visual","descripcion":"Dashboard bonito para presentar KPIs del servicio a la directora: gráficos, colores corporativos, responsive.","dominio":"GESTION"},
   {"titulo":"Formulario de satisfacción","descripcion":"Encuesta para evaluar satisfacción del servicio de farmacia desde plantas. Diseño limpio, responsive, exporta datos.","dominio":"GESTION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["diseño","React","bonito","web","prototipo"]', 5),

('v0', 'https://v0.dev', '🔲',
 'Genera componentes React/UI desde prompts, ideal para dashboards',
 'v0 de Vercel genera componentes React de alta calidad desde prompts. Especializado en UI: tablas, gráficos, formularios, dashboards. Código limpio con Tailwind CSS.',
 'DESARROLLO', 'Vercel',
 'Gratis: 10 generaciones/día, preview, copiar código',
 'Premium 20$/mes: generaciones ilimitadas, proyectos privados.',
 '["Componentes React de alta calidad","Tailwind CSS profesional","Ideal para dashboards","Código limpio y reutilizable"]',
 '["Solo componentes, no apps completas","Requiere conocimientos React para integrar","Plan gratis limitado"]',
 '[{"titulo":"Dashboard de KPIs farmacéuticos","descripcion":"Genera: tabla sortable con filtros de indicadores SEFH, gráfico de barras de intervenciones por farmacéutico, mini-cards con totales. Código React listo.","dominio":"GESTION"},
   {"titulo":"Tabla de equidad de guardias","descripcion":"Genera componente React para tabla de equidad: farmacéuticos × tipos de guardia, celdas coloreadas por desviación. Exporta código.","dominio":"DESARROLLO"},
   {"titulo":"Formulario de validación farmacéutica","descripcion":"Genera formulario complejo: datos paciente, tratamiento, analíticas, con validación en tiempo real y envío a API.","dominio":"DESARROLLO"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["React","componentes","UI","dashboard","Tailwind"]', 6),

('Replit', 'https://replit.com', '🔄',
 'IDE online con IA, despliega apps sin instalar nada',
 'Replit es un IDE completo en el navegador con IA integrada. Escribes, ejecutas y despliegas todo online. Soporta Python, JavaScript, y 50+ lenguajes.',
 'DESARROLLO', 'Replit',
 'Gratis: IDE online, ejecución, Ghostwriter básico',
 'Pro 25$/mes: Ghostwriter avanzado, más recursos, deploy.',
 '["IDE completo en el navegador","Despliega sin configurar servidor","Soporta 50+ lenguajes","Colaboración en tiempo real"]',
 '["Lento vs IDE local","Almacenamiento limitado en plan gratis","Ghostwriter menos potente que Copilot","Dependencia de internet"]',
 '[{"titulo":"Script rápido de análisis de datos","descripcion":"Sube CSV de consumos. Escribe script Python que analiza tendencias, genera gráficos y exporta informe. Todo en el navegador.","dominio":"GESTION"},
   {"titulo":"Bot de Telegram para alertas","descripcion":"Crea bot que envía alertas de Telegram cuando un paciente tiene analítica crítica. Python + Telegram API, desplegado en Replit.","dominio":"DESARROLLO"},
   {"titulo":"API mockup para prototipo","descripcion":"Necesitas probar el frontend antes de tener la API real. Crea API fake con datos simulados en Replit en 10 minutos.","dominio":"DESARROLLO"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["IDE online","deploy","Python","navegador"]', 7),

('Make', 'https://make.com', '⚙️',
 'Automatización visual de flujos: conecta APIs sin programar',
 'Make (antes Integromat) permite crear flujos de automatización conectando APIs y servicios sin escribir código. Arrastra y conecta módulos visualmente.',
 'DESARROLLO', 'Make',
 'Gratis: 1000 operaciones/mes, 2 escenarios activos',
 'Core 9€/mes: 10.000 ops, escenarios ilimitados.',
 '["Automatización sin código","Interfaz visual drag-and-drop","1000+ integraciones","Ideal para flujos repetitivos"]',
 '["1000 ops/mes en plan gratis limitado","Flujos complejos difíciles de debuggear","Dependencia de servicio cloud","No para procesamiento pesado de datos"]',
 '[{"titulo":"Alerta automática de papers nuevos","descripcion":"Flujo: PubMed RSS → filtrar por keywords → traducir con DeepL → enviar a Slack/email del servicio. Sin una línea de código.","dominio":"INVESTIGACION"},
   {"titulo":"Backup automático de datos","descripcion":"Cada lunes: exportar datos de SIGFAR Hub → guardar en Google Drive → notificar por email. Automatizado con Make.","dominio":"GESTION"},
   {"titulo":"Reporting automático","descripcion":"Cada viernes: obtener KPIs de SIGFAR API → generar tabla → enviar email a la directora con resumen semanal.","dominio":"GESTION"}]',
 'MEDIO', 'CLOUD_CON_DPA', TRUE,
 '["automatización","no-code","flujos","APIs","integración"]', 8),

('n8n', 'https://n8n.io', '🔧',
 'Alternativa open-source a Make, self-hosted, ideal para hospital',
 'n8n es una plataforma de automatización open-source que puedes ejecutar en tu propio servidor. Los datos nunca salen de tu infraestructura, ideal para el entorno hospitalario.',
 'DESARROLLO', 'n8n GmbH',
 'Gratis: self-hosted ilimitado, community edition',
 'Cloud 20€/mes: hosted, soporte, certificados.',
 '["Open-source y self-hosted","Datos nunca salen del hospital","Flujos visuales como Make","Nodos personalizables con JavaScript","Docker: fácil de desplegar"]',
 '["Requiere administración del servidor","Curva de aprendizaje mayor que Make","Menos integraciones pre-construidas","Documentación menos completa"]',
 '[{"titulo":"Pipeline de datos dentro del hospital","descripcion":"n8n en Docker del hospital: lee datos de ICCA (HL7) → transforma → inserta en SIGFAR Hub (PostgreSQL). Datos nunca salen de la red.","dominio":"DESARROLLO"},
   {"titulo":"Alertas internas automatizadas","descripcion":"Monitoriza tabla de analíticas. Si K+ > 6.0 + espironolactona: envía alerta interna al farmacéutico de guardia. Todo dentro del hospital.","dominio":"VALIDACION"},
   {"titulo":"ETL para cuadro de mandos","descripcion":"Extrae datos de SIGFAR + GestionAX cada noche, transforma, carga en tabla de KPIs. Datos nunca salen de la red del hospital.","dominio":"GESTION"}]',
 'AVANZADO', 'LOCAL', FALSE,
 '["automatización","open-source","self-hosted","hospital","Docker"]', 9),

('Antigravity', 'https://antigravity.dev', '🚀',
 'Plataforma de desarrollo IA para proyectos complejos multi-agente',
 'Antigravity es una plataforma para construir sistemas de IA complejos con múltiples agentes coordinados. Ideal para proyectos como SIGFAR Hub que necesitan orquestación de agentes.',
 'DESARROLLO', 'Antigravity',
 'Beta: acceso temprano gratuito',
 'Pendiente de definir pricing.',
 '["Orquestación de múltiples agentes IA","Ideal para sistemas complejos","Interfaz visual de flujos de agentes","Soporta múltiples modelos"]',
 '["En beta temprana","Documentación escasa","Curva de aprendizaje alta","Viabilidad a largo plazo incierta"]',
 '[{"titulo":"Pipeline multiagente de validación","descripcion":"Orquestar 6 agentes PCNE de SIGFAR P15: cada uno analiza un tipo de EM/PRM, coordinados por Antigravity que gestiona el flujo y consenso.","dominio":"VALIDACION"},
   {"titulo":"Sistema multi-IA con consenso","descripcion":"La propuesta estratégica de Multi-IA Consenso: enviar paciente a 3 modelos en paralelo, comparar, consensuar. Antigravity coordina el flujo.","dominio":"DESARROLLO"},
   {"titulo":"Vigilancia proactiva automatizada","descripcion":"Sistema que cada hora: lee pacientes → distribuye entre agentes → cada agente analiza su área → consolida alertas → prioriza → notifica.","dominio":"VALIDACION"}]',
 'AVANZADO', 'CLOUD_ANONIMIZAR', TRUE,
 '["agentes","orquestación","multi-agente","complejo"]', 10),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 7: IMAGEN_MULTIMEDIA (8 herramientas)
-- ═══════════════════════════════════════════════════════════════

('DALL-E 3', 'https://chat.openai.com', '🖼️',
 'Generación de imágenes desde texto, integrado en ChatGPT',
 'DALL-E 3 genera imágenes de alta calidad a partir de descripciones textuales. Integrado directamente en ChatGPT. Entiende prompts complejos y genera imágenes muy fieles a la descripción.',
 'IMAGEN_MULTIMEDIA', 'OpenAI',
 'Gratis: 2 imágenes/día en ChatGPT Free',
 'Plus 20$/mes: DALL-E ilimitado.',
 '["Integrado en ChatGPT (sin app separada)","Entiende prompts complejos","Alta calidad y fidelidad","Genera texto en imágenes (logos, etiquetas)"]',
 '["Solo 2/día en plan gratis","No genera personas reales","Estilo a veces demasiado ilustrativo","Sin edición granular de la imagen"]',
 '[{"titulo":"Imágenes para presentaciones","descripcion":"Genera: imagen profesional de un farmacéutico revisando datos en pantalla con IA, estilo corporativo, colores verdes del hospital. Para slide de la ponencia.","dominio":"COMUNICACION"},
   {"titulo":"Portadas para informes","descripcion":"Genera portada para el informe anual del servicio: representación artística de farmacia hospitalaria + tecnología + IA. Profesional y moderna.","dominio":"GESTION"},
   {"titulo":"Esquemas conceptuales","descripcion":"Genera diagrama conceptual de la arquitectura SIGFAR Hub: nodos conectados, flujos de datos, estilo infográfico. Para documentación.","dominio":"COMUNICACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["imágenes","generación","ChatGPT","portadas","presentaciones"]', 1),

('Midjourney', 'https://midjourney.com', '🎨',
 'Imágenes de altísima calidad artística desde prompts detallados',
 'Midjourney genera imágenes de calidad artística excepcional. Los resultados son más estéticos y creativos que DALL-E. Ideal para posters de congreso, material de impacto visual.',
 'IMAGEN_MULTIMEDIA', 'Midjourney',
 'Sin plan gratis actualmente.',
 'Basic 10$/mes: 200 generaciones. Standard 30$/mes: ilimitado.',
 '["Calidad artística superior","Estilos fotorrealistas y artísticos","Excelente para material de impacto","Parámetros avanzados de estilo"]',
 '["Sin plan gratis","Interfaz via Discord (no intuitiva)","Requiere prompts detallados en inglés","Sin API oficial aún"]',
 '[{"titulo":"Poster artístico para congreso","descripcion":"Genera imagen principal del poster: representación artística de IA asistiendo a farmacéutico en hospital. Calidad que impresiona en el congreso.","dominio":"COMUNICACION"},
   {"titulo":"Infografía de alto impacto","descripcion":"Imagen central para infografía del programa PROA: representación visual de datos + IA + antimicrobianos. Estilo corporativo.","dominio":"COMUNICACION"},
   {"titulo":"Material formativo visual","descripcion":"Serie de imágenes para módulo formativo de IA en farmacia: 10 slides con imágenes conceptuales de cada aplicación de IA.","dominio":"FORMACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["arte","calidad","posters","impacto visual"]', 2),

('Google ImageFX', 'https://aitestkitchen.withgoogle.com/tools/image-fx', '🖌️',
 'Generador gratuito de Google, buena calidad sin coste',
 'ImageFX de Google genera imágenes desde texto de forma totalmente gratuita. Calidad buena aunque menor que Midjourney. Ideal para generar imágenes rápidas sin coste.',
 'IMAGEN_MULTIMEDIA', 'Google',
 'Gratis: generaciones ilimitadas',
 'Gratis.',
 '["Completamente gratis","Buena calidad de imagen","Sin registro (solo Google account)","Rápido y fácil de usar"]',
 '["Menor calidad que Midjourney/DALL-E","Filtros estrictos (rechaza muchos prompts)","Sin API","Control limitado de estilo"]',
 '[{"titulo":"Imágenes rápidas sin coste","descripcion":"Necesitas imagen para la sesión de mañana: farmacéutico trabajando con IA en hospital. ImageFX la genera gratis en 30 segundos.","dominio":"COMUNICACION"},
   {"titulo":"Ilustraciones para formación","descripcion":"Material para residentes: genera ilustraciones de conceptos PK (modelo bicompartimental, curva concentración-tiempo). Gratis.","dominio":"FORMACION"},
   {"titulo":"Imágenes para redes sociales","descripcion":"El servicio de farmacia quiere publicar en LinkedIn. ImageFX genera imagen profesional del equipo + IA. Sin coste.","dominio":"COMUNICACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["gratis","imágenes","Google","rápido"]', 3),

('Remove.bg', 'https://remove.bg', '✂️',
 'Elimina fondos de fotos automáticamente con IA',
 'Remove.bg elimina el fondo de cualquier imagen automáticamente en 5 segundos. Perfecto para fotos de equipo, productos, preparaciones.',
 'IMAGEN_MULTIMEDIA', 'Kaleido AI',
 'Gratis: baja resolución, 1 imagen de alta/mes',
 'Pay-as-you-go: desde 9€/40 créditos. Suscripción desde 39€/mes.',
 '["Elimina fondo en 5 segundos","Resultado profesional","API disponible","Funciona con fotos complejas"]',
 '["Baja resolución en plan gratis","Caro para uso frecuente","Solo elimina fondo (no edita)"]',
 '[{"titulo":"Fotos de equipo profesionales","descripcion":"Foto del equipo de farmacia con fondo desordenado del servicio → remove.bg → fondo blanco profesional para la web del hospital.","dominio":"COMUNICACION"},
   {"titulo":"Catálogo visual de preparaciones","descripcion":"Fotos de preparaciones magistrales con fondo de la cabina → remove.bg → fondo blanco para catálogo visual del servicio.","dominio":"ELABORACION"},
   {"titulo":"Material formativo limpio","descripcion":"Fotos de dispositivos de administración con fondo despejado para material formativo de enfermería.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', FALSE,
 '["fondos","fotos","edición","profesional"]', 4),

('Otter.ai', 'https://otter.ai', '🎙️',
 'Transcripción automática de reuniones y sesiones con resumen IA',
 'Otter.ai transcribe reuniones y conversaciones en tiempo real con IA. Genera resúmenes automáticos, identifica hablantes, y permite buscar dentro de las transcripciones.',
 'IMAGEN_MULTIMEDIA', 'Otter.ai',
 'Gratis: 300 min/mes transcripción, resúmenes',
 'Pro 17$/mes: 1200 min, integraciones Zoom/Teams/Meet.',
 '["Transcripción en tiempo real","Identifica hablantes automáticamente","Genera resúmenes de reuniones","Búsqueda dentro de transcripciones","Integración Zoom/Teams/Meet"]',
 '["Solo en inglés (español limitado)","300 min/mes en plan gratis","Requiere audio claro","Terminología médica puede fallar"]',
 '[{"titulo":"Transcribir sesiones clínicas","descripcion":"Graba la sesión de servicio semanal. Otter transcribe automáticamente, identifica quién habla, y genera resumen con decisiones y tareas.","dominio":"GESTION"},
   {"titulo":"Documentar reuniones con dirección","descripcion":"Reunión con gerencia sobre presupuesto del servicio. Otter transcribe todo y genera acta automática con puntos clave y acuerdos.","dominio":"GESTION"},
   {"titulo":"Grabaciones formativas","descripcion":"El adjunto da clase sobre TDM. Otter transcribe la clase. Los residentes pueden buscar dentro de la transcripción: ¿qué dijo sobre el loading dose?","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["transcripción","reuniones","sesiones","resumen","audio"]', 5),

('Descript', 'https://descript.com', '🎬',
 'Edición de vídeo/audio como si editaras un documento de texto',
 'Descript permite editar vídeo y audio editando la transcripción. Borras palabras del texto y se borran del vídeo. Ideal para crear contenido formativo sin conocimientos de edición.',
 'IMAGEN_MULTIMEDIA', 'Descript',
 'Gratis: 1 hora de transcripción, edición básica',
 'Pro 24$/mes: ilimitado, IA voz, pantalla verde, exportar.',
 '["Edición de vídeo editando texto","Elimina muletillas automáticamente","Genera subtítulos","Clonación de voz (IA)","Pantalla verde virtual"]',
 '["Plan gratis limitado (1 hora)","Curva de aprendizaje inicial","Exportación pesada","Solo en inglés para funciones IA avanzadas"]',
 '[{"titulo":"Vídeos formativos para residentes","descripcion":"Grabas explicación de 20 min sobre PK de vancomicina. Descript transcribe, eliminas las muletillas automáticamente, añades subtítulos. Vídeo profesional sin saber editar.","dominio":"FORMACION"},
   {"titulo":"Clips de sesiones clínicas","descripcion":"De la sesión de 1 hora, seleccionas 3 fragmentos clave editando el texto. Descript corta los clips automáticamente. Compartes con el equipo.","dominio":"FORMACION"},
   {"titulo":"Podcast del servicio","descripcion":"Graba podcast mensual con novedades del servicio. Descript edita, elimina errores, añade intro/outro. Publicar en Spotify.","dominio":"COMUNICACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["vídeo","audio","edición","formación","podcast"]', 6),

('ElevenLabs', 'https://elevenlabs.io', '🔊',
 'Síntesis de voz ultra-realista, ideal para material formativo audio',
 'ElevenLabs genera voz artificial indistinguible de la humana. Permite crear material de audio formativo, narrar presentaciones, o generar podcasts sin grabar con micrófono.',
 'IMAGEN_MULTIMEDIA', 'ElevenLabs',
 'Gratis: 10.000 caracteres/mes, voces predefinidas',
 'Starter 5$/mes: 30.000 chars, clonación voz, API.',
 '["Voz ultra-realista en español","Múltiples voces y acentos","Clonación de voz (copia tu propia voz)","API para automatizar","Genera audiolibros y podcasts"]',
 '["Solo 10K chars gratis (≈5 min audio)","Clonación de voz plantea cuestiones éticas","En español algo menos natural que en inglés","Caro para uso extensivo"]',
 '[{"titulo":"Narrar presentaciones","descripcion":"Tu ponencia tiene 30 slides. ElevenLabs narra cada slide: generas vídeo con tu presentación + voz profesional. Sin grabarte.","dominio":"COMUNICACION"},
   {"titulo":"Material audio para residentes","descripcion":"Genera audio de 15 min explicando el protocolo PROA. Los residentes lo escuchan como podcast mientras viajan al hospital.","dominio":"FORMACION"},
   {"titulo":"Accesibilidad de protocolos","descripcion":"Convierte los PNTs escritos en audio para personal con dificultades de lectura o para escuchar mientras trabaja.","dominio":"GESTION"}]',
 'FACIL', 'CLOUD_ANONIMIZAR', TRUE,
 '["voz","audio","síntesis","podcast","narración"]', 7),

('Photopea', 'https://photopea.com', '🖼️',
 'Photoshop gratuito online con funciones de edición avanzada',
 'Photopea es un editor de imágenes online gratuito con interfaz idéntica a Photoshop. Soporta PSD, capas, filtros, y funciones de IA como generación y eliminación de objetos.',
 'IMAGEN_MULTIMEDIA', 'Photopea',
 'Gratis: todas las funciones, con anuncios',
 'Premium 5$/mes: sin anuncios.',
 '["Gratis con todas las funciones","Interfaz idéntica a Photoshop","Soporta PSD, RAW, SVG","No requiere instalación","Funciones IA: generación, eliminación"]',
 '["Con anuncios en plan gratis","Requiere conexión a internet","Menos potente que Photoshop nativo","Curva de aprendizaje si no conoces Photoshop"]',
 '[{"titulo":"Editar posters de congreso","descripcion":"Ajusta colores, añade logos del hospital, redimensiona para impresión A0. Todo gratis en el navegador.","dominio":"COMUNICACION"},
   {"titulo":"Crear infografías personalizadas","descripcion":"Combina gráficos de SIGFAR Hub con imágenes y texto para crear infografía personalizada del servicio.","dominio":"COMUNICACION"},
   {"titulo":"Editar fotos de equipo","descripcion":"Ajusta brillo, contraste, recorta fotos del equipo para la memoria anual del servicio.","dominio":"GESTION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', FALSE,
 '["edición","Photoshop","gratis","imágenes","diseño"]', 8),

-- ═══════════════════════════════════════════════════════════════
-- CATEGORÍA 8: SALUD_FARMA (10 herramientas)
-- ═══════════════════════════════════════════════════════════════

('Glass Health', 'https://glass.health', '🏥',
 'Generador de diagnósticos diferenciales y planes clínicos con IA',
 'Glass Health genera diagnósticos diferenciales y planes de tratamiento basados en los datos del paciente. Diseñado específicamente para profesionales sanitarios. Puede ayudar al farmacéutico a entender la perspectiva clínica.',
 'SALUD_FARMA', 'Glass Health',
 'Gratis: uso básico con cuenta, DDx y planes',
 'Pro (institucional): features avanzadas.',
 '["Diseñado para profesionales sanitarios","DDx basado en datos del paciente","Planes de tratamiento estructurados","Interfaz limpia y clínica"]',
 '["Orientado a médicos más que a farmacéuticos","No tiene perspectiva farmacéutica","Basado en evidencia americana (FDA)","Requiere adaptación al contexto español"]',
 '[{"titulo":"Entender perspectiva clínica del médico","descripcion":"Paciente con fiebre+neutropenia post-quimio. Glass genera DDx y plan. El farmacéutico entiende qué ATB empírico elegirá el médico y prepara su revisión.","dominio":"VALIDACION"},
   {"titulo":"Formación en casos clínicos","descripcion":"R1 practica: introduce datos del paciente y compara su DDx con el de Glass. Feedback inmediato.","dominio":"FORMACION"},
   {"titulo":"Soporte para interconsultas","descripcion":"Interconsulta de planta: ¿qué tratamiento para endocarditis por SARM en paciente con IR? Glass sugiere plan, farmacéutico revisa y ajusta dosis.","dominio":"VALIDACION"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["diagnóstico","clínica","DDx","tratamiento"]', 1),

('DoseMeRx', 'https://doseme-rx.com', '💊',
 'TDM con IA: calcula dosis de vancomicina, aminoglucósidos con modelos bayesianos',
 'DoseMeRx es una plataforma de dosificación de precisión que usa modelos farmacocinéticos bayesianos para calcular dosis individualizadas. Soporta vancomicina, aminoglucósidos, voriconazol, y 50+ fármacos.',
 'SALUD_FARMA', 'DoseMe',
 'Demo gratuita disponible. Requiere licencia institucional.',
 'Institucional: consultar precios. Desde ~5.000€/año.',
 '["Modelos PK bayesianos validados","50+ fármacos soportados","Interfaz diseñada para farmacéuticos","Predicción AUC/MIC para vancomicina","Integración con HCE vía FHIR"]',
 '["Requiere licencia institucional (caro)","No open-source","Modelos pre-definidos (no customizables)","Requiere datos de niveles séricos"]',
 '[{"titulo":"Alternativa comercial a P42","descripcion":"DoseMeRx hace lo mismo que nuestro P42 (TDM bayesiano) pero comercialmente. SIGFAR P42 es gratuito y personalizable. DoseMeRx es referencia para benchmarking.","dominio":"FARMACOCINETICA"},
   {"titulo":"Validar nuestros modelos PK","descripcion":"Comparar resultados de P42 (MAP bayesiano de SIGFAR) con DoseMeRx para los mismos pacientes. Validación cruzada.","dominio":"FARMACOCINETICA"},
   {"titulo":"TDM de fármacos no cubiertos por P42","descripcion":"P42 cubre vancomicina, gentamicina, amikacina. DoseMeRx cubre voriconazol, tacrolimus, fenitoína. Complementarios.","dominio":"FARMACOCINETICA"}]',
 'AVANZADO', 'CLOUD_CON_DPA', TRUE,
 '["TDM","bayesiano","vancomicina","dosificación","PK"]', 2),

('Viz.ai', 'https://viz.ai', '🧠',
 'Detección IA en imagen médica: ACV, embolismo pulmonar, aneurisma',
 'Viz.ai utiliza IA para detectar patologías en imagen médica (ACV, embolismo pulmonar, aneurisma aórtico) y alertar al equipo en tiempo real. Aprobado por FDA.',
 'SALUD_FARMA', 'Viz.ai',
 'No disponible gratis. Institucional.',
 'Institucional: consultar. Típicamente 50-100K$/año.',
 '["Aprobado FDA para múltiples patologías","Alertas en tiempo real al equipo","Reduce tiempo puerta-aguja en ACV","Integración con PACS hospitalario"]',
 '["Muy caro (institucional)","No directamente útil para farmacia","Requiere integración con imagen","Solo imagen médica"]',
 '[{"titulo":"Conocer detección precoz de ACV","descripcion":"Si el hospital implementa Viz.ai, el farmacéutico debe conocer que la trombolisis se activará más rápido. Preparar alteplasa + protocolo.","dominio":"VALIDACION"},
   {"titulo":"Referencia para IA regulada","descripcion":"Viz.ai es ejemplo de IA con marcado CE y FDA clearance. Referencia para el módulo de Regulación y para justificar IA en farmacia.","dominio":"GESTION"},
   {"titulo":"Benchmark de IA en hospital","descripcion":"Si el hospital ya usa Viz.ai en radiología, argumento para implementar IA en farmacia: si radiología ya tiene IA aprobada, farmacia también puede.","dominio":"GESTION"}]',
 'AVANZADO', 'CLOUD_CON_DPA', TRUE,
 '["imagen médica","FDA","ACV","diagnóstico","hospital"]', 3),

('Regard', 'https://regard.com', '📋',
 'Asistente clínico IA que lee historiales y sugiere diagnósticos automáticamente',
 'Regard analiza automáticamente historiales clínicos electrónicos y sugiere diagnósticos que el clínico podría estar pasando por alto. Reduce diagnósticos perdidos en un 30%.',
 'SALUD_FARMA', 'Regard',
 'No disponible gratis. Institucional.',
 'Institucional: consultar precios.',
 '["Analiza HCE automáticamente","Sugiere diagnósticos pasados por alto","Reduce errores diagnósticos","Integración con HCE principales"]',
 '["Institucional (muy caro)","Orientado a diagnóstico médico","No disponible en España aún","Requiere integración HCE"]',
 '[{"titulo":"Detección de diagnósticos ocultos que afectan a la farmacoterapia","descripcion":"Si Regard detecta diabetes no diagnosticada en paciente con metformina, el farmacéutico puede anticipar ajuste de tratamiento.","dominio":"VALIDACION"},
   {"titulo":"Referencia para vigilancia proactiva","descripcion":"Lo que Regard hace para diagnósticos, SIGFAR Hub lo hace para farmacoterapia: analizar automáticamente y alertar. Mismo concepto, diferente dominio.","dominio":"VALIDACION"},
   {"titulo":"Benchmark de IA en HCE","descripcion":"Regard es referencia de cómo integrar IA en el historial clínico. Modelo para futuro módulo SIGFAR que lea Hosix/Florence.","dominio":"DESARROLLO"}]',
 'AVANZADO', 'CLOUD_CON_DPA', TRUE,
 '["HCE","diagnóstico","historial","IA clínica"]', 4),

('Abridge', 'https://abridge.com', '🎤',
 'Documentación clínica automática desde conversaciones médico-paciente',
 'Abridge escucha la conversación entre médico y paciente y genera automáticamente la nota clínica estructurada. Reduce tiempo de documentación un 50%.',
 'SALUD_FARMA', 'Abridge',
 'No disponible gratis. Institucional.',
 'Institucional: consultar. Integrado en Epic.',
 '["Documentación automática desde voz","Nota clínica estructurada","Integración con Epic","Reduce 50% tiempo documentación"]',
 '["Institucional (caro)","Solo inglés por ahora","Requiere integración HCE","Cuestiones privacidad conversaciones"]',
 '[{"titulo":"Inspiración para documentación farmacéutica","descripcion":"Si Abridge documenta automáticamente consultas médicas, ¿podemos documentar automáticamente la atención farmacéutica? Dictado → POF estructurado.","dominio":"GESTION"},
   {"titulo":"Conciliación al alta desde conversación","descripcion":"Concepto futuro: el farmacéutico habla con el paciente al alta, Abridge-like genera automáticamente el informe de conciliación.","dominio":"VALIDACION"},
   {"titulo":"Benchmark de NLP clínico","descripcion":"Abridge es referencia de cómo la voz + NLP puede transformar la documentación clínica. Modelo para SIGFAR.","dominio":"DESARROLLO"}]',
 'AVANZADO', 'CLOUD_CON_DPA', TRUE,
 '["voz","documentación","NLP","consulta","automático"]', 5),

('DrugBank', 'https://go.drugbank.com', '💉',
 'Base de datos de fármacos con API: interacciones, targets, farmacocinética',
 'DrugBank es la base de datos de fármacos más completa del mundo. Incluye interacciones, targets moleculares, farmacocinética, metabolismo, y más. API disponible para integración. Open data parcialmente gratuito.',
 'SALUD_FARMA', 'OMx Personal Health Analytics',
 'Gratis: datos open access, búsqueda web',
 'API: desde 200$/mes. Academic: gratis con solicitud.',
 '["Base de datos de fármacos más completa","API REST para integración","Interacciones, targets, PK","Datos curados manualmente","Academic license gratuita"]',
 '["API cara para uso comercial","Datos técnicos, no clínicos","En inglés","Requiere conocimientos bioinformática para API"]',
 '[{"titulo":"Verificar mecanismo de interacción","descripcion":"¿Por qué interaccionan fluconazol y ciclosporina? DrugBank muestra: fluconazol inhibe CYP3A4, que metaboliza ciclosporina. Mecanismo molecular claro.","dominio":"VALIDACION"},
   {"titulo":"Investigar farmacocinética detallada","descripcion":"Datos PK de un fármaco nuevo: biodisponibilidad, Vd, t½, clearance, unión a proteínas, metabolismo CYP. Todo en DrugBank.","dominio":"FARMACOCINETICA"},
   {"titulo":"Integrar en SIGFAR Hub vía API","descripcion":"API de DrugBank (si academic license) para enriquecer automáticamente los datos de interacciones de P15 con mecanismos moleculares.","dominio":"DESARROLLO"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', FALSE,
 '["fármacos","interacciones","API","PK","mecanismo"]', 6),

('Pharmacist.AI', 'https://pharmacist.ai', '⚕️',
 'Herramientas IA específicas para farmacéuticos en desarrollo',
 'Pharmacist.AI es una plataforma en desarrollo que pretende ofrecer herramientas de IA específicamente diseñadas para el flujo de trabajo del farmacéutico: validación, TDM, PROA, gestión.',
 'SALUD_FARMA', 'Pharmacist.AI',
 'En desarrollo. Beta limitada.',
 'Pendiente de definir.',
 '["Diseñado específicamente para farmacéuticos","Flujo de trabajo farmacéutico nativo","Potencial: validación, TDM, PROA integrados"]',
 '["En desarrollo (no disponible aún)","Viabilidad comercial incierta","Sin track record","Puede no llegar al mercado"]',
 '[{"titulo":"Seguir de cerca para benchmarking","descripcion":"Si Pharmacist.AI llega al mercado, comparar sus features con SIGFAR. ¿Hacen lo mismo? ¿Algo diferente? Benchmark competitivo.","dominio":"GESTION"},
   {"titulo":"Referencia para publicación","descripcion":"Si publicamos sobre SIGFAR, citar Pharmacist.AI como iniciativa paralela en el sector. Muestra que la IA en farmacia es tendencia global.","dominio":"INVESTIGACION"},
   {"titulo":"Posible colaboración","descripcion":"Si se desarrolla, explorar sinergias: ¿pueden integrarse en SIGFAR? ¿Ofrecen API? ¿Modelo complementario?","dominio":"DESARROLLO"}]',
 'MEDIO', 'CLOUD_ANONIMIZAR', TRUE,
 '["farmacéutico","validación","TDM","PROA","especializado"]', 7),

('MedPaLM', 'https://cloud.google.com/medpalm', '🔬',
 'LLM especializado en medicina de Google (acceso limitado investigación)',
 'MedPaLM es un modelo de lenguaje de Google entrenado específicamente para medicina. Ha alcanzado nivel de experto médico en exámenes USMLE. Acceso limitado a instituciones de investigación.',
 'SALUD_FARMA', 'Google',
 'Acceso por solicitud para investigación.',
 'No disponible comercialmente. Solo investigación.',
 '["Nivel experto en exámenes médicos (USMLE)","Entrenado específicamente en medicina","Menos alucinaciones en contexto clínico","Respaldado por Google"]',
 '["Acceso muy restringido","No disponible comercialmente","Sin API pública","Solo inglés","No específico para farmacia"]',
 '[{"titulo":"Referencia de IA médica especializada","descripcion":"MedPaLM es el benchmark de IA médica. Si SIGFAR compara sus resultados con MedPaLM en detección de EM/PRM, fortalece la evidencia.","dominio":"INVESTIGACION"},
   {"titulo":"Futuro: modelo médico para SIGFAR","descripcion":"Cuando MedPaLM o similar sea accesible, podría ser alternativa a Llama para tareas clínicas en SIGFAR. Más preciso en razonamiento médico.","dominio":"DESARROLLO"},
   {"titulo":"Publicación comparativa","descripcion":"Paper comparando: SIGFAR (Llama 70B open-source) vs MedPaLM (Google especializado) en detección de EM/PRM. Contribución científica significativa.","dominio":"INVESTIGACION"}]',
 'AVANZADO', 'CLOUD_CON_DPA', TRUE,
 '["médico","especializado","Google","USMLE","investigación"]', 8),

('BioGPT', 'https://github.com/microsoft/BioGPT', '🧬',
 'LLM biomédico open-source de Microsoft para investigación farmacéutica',
 'BioGPT de Microsoft es un modelo de lenguaje pre-entrenado con literatura biomédica. Open-source, puede ejecutarse localmente. Especializado en extracción de relaciones biomédicas y QA sobre papers.',
 'SALUD_FARMA', 'Microsoft Research',
 'Gratis: open-source, ejecutar localmente',
 'Gratis (open-source MIT license).',
 '["Open-source (ejecutar localmente)","Entrenado en literatura biomédica","Extracción de relaciones fármaco-enfermedad","Puede fine-tunearse con datos propios","Sin enviar datos a la nube"]',
 '["Modelo pequeño (menos capaz que GPT-4)","Solo inglés","Requiere conocimientos de ML para usar","No tiene interfaz chat user-friendly","Necesita GPU para rendimiento aceptable"]',
 '[{"titulo":"Extracción de relaciones de papers","descripcion":"BioGPT extrae automáticamente relaciones fármaco-enfermedad-gen de papers de PubMed. Útil para la base de conocimiento de SIGFAR.","dominio":"INVESTIGACION"},
   {"titulo":"Fine-tuning con datos de farmacia","descripcion":"Entrenar BioGPT con datos anonimizados de SIGFAR (EM/PRM, intervenciones) para crear modelo especializado en farmacia hospitalaria española.","dominio":"DESARROLLO"},
   {"titulo":"NER biomédico local","descripcion":"Ejecutar BioGPT localmente para Named Entity Recognition: extraer nombres de fármacos, diagnósticos, dosis de texto libre. Sin enviar datos fuera.","dominio":"DESARROLLO"}]',
 'AVANZADO', 'LOCAL', FALSE,
 '["open-source","biomédico","NER","local","fine-tuning"]', 9),

('UpToDate', 'https://uptodate.com', '📖',
 'Base de evidencia clínica point-of-care con soporte a decisiones',
 'UpToDate es la referencia mundial de evidencia clínica point-of-care. Usado por millones de clínicos para consultar tratamientos, diagnósticos y guías basadas en evidencia.',
 'SALUD_FARMA', 'Wolters Kluwer',
 'No gratis. Requiere suscripción institucional.',
 'Institucional: ~15.000-50.000€/año según tamaño.',
 '["Referencia mundial en evidencia clínica","Actualizado continuamente","Recomendaciones graduadas por evidencia","Calculadoras clínicas integradas","Drug information completa"]',
 '["Muy caro (institucional)","No tiene API para integración","Contenido en inglés principalmente","No específico para farmacia"]',
 '[{"titulo":"Consulta point-of-care","descripcion":"¿Tratamiento empírico de endocarditis por SARM en paciente con IR? UpToDate da recomendación con grado de evidencia, dosis, monitorización.","dominio":"VALIDACION"},
   {"titulo":"Drug information","descripcion":"Sección de farmacología completa: PK, interacciones, dosis en IR/IH, embarazo, lactancia. Referencia estándar.","dominio":"VALIDACION"},
   {"titulo":"Formación de residentes","descripcion":"Los FIR deben saber usar UpToDate como referencia principal. Formación en cómo buscar y evaluar recomendaciones.","dominio":"FORMACION"}]',
 'FACIL', 'CLOUD_CON_DPA', TRUE,
 '["evidencia","point-of-care","tratamiento","guías","referencia"]', 10);
